openapi: "3.0.0"
info:
  version: 1.0.0
  title: Directoryish API
paths:
  /consortia:
    get:
      summary: Returns all consortia
      description: Returns all consortia the user has access to.
      operationId: getConsortia
      parameters:
        - name: q
          in: query
          description: keywords to filter by
          required: false
          style: form
          schema:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Consortium list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consortium'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: Creates a new consortium
      description: Creates a new consortium
      operationId: addConsortium
      requestBody:
        description: Consortium to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consortium'
      responses:
        '201':
          description: Consortium response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Id'
          links:
            GetConsortiumByID:
              operationId: getConsortium
              parameters:
                id: '$response.body#/id'
            # UpdateConsortium:
            #   operationId: updateConsortium
            #   parameters:
            #     id: '$response.body#/id'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
  /consortia/{id}:
    get:
      summary: Returns a consortium by ID
      operationId: getConsortium
      parameters:
        - name: id
          in: path
          description: ID of consortium to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Consortium response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consortium'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Entry not found
          content:
            text/plain:
              schema:
                type: string
    patch:
      summary: Update a consortium
      description: Update a consortium
      operationId: updateConsortium
      parameters:
        - name: id
          in: path
          description: ID of consortium to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated fields
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsortiumPatch'
      responses:
        '204':
          description: Consortium updated
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Entry not found
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: Delete consortium by ID
      operationId: deleteConsortium
      parameters:
        - name: id
          in: path
          description: ID of consortium to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: consortium deleted
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
  /entries:
    get:
      summary: Returns all entries
      description: Returns all entries from the system that the user has access to.
      operationId: getEntries
      parameters:
        - name: q
          in: query
          description: keywords to filter by
          required: false
          style: form
          schema:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Entry list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entry'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: Creates a new entry
      description: Creates a new entry
      operationId: addEntry
      requestBody:
        description: Entry to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entry'
      responses:
        '201':
          description: Entry response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Id'
          links:
            GetEntryByID:
              operationId: getEntryByID
              parameters:
                id: '$response.body#/id'
            UpdateEntry:
              operationId: updateEntry
              parameters:
                id: '$response.body#/id'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
  /entries/by-id/{id}:
    get:
      summary: Returns a directory entry by ID
      operationId: getEntryByID
      parameters:
        - name: id
          in: path
          description: ID of entry to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Entry response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Entry not found
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string
    patch:
      summary: Update an entry
      description: Update an entry
      operationId: updateEntry
      parameters:
        - name: id
          in: path
          description: ID of entry to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated fields
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryPatch'
      responses:
        '204':
          description: entry updated
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Entry not found
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: Delete directory entry by ID
      operationId: deleteEntry
      parameters:
        - name: id
          in: path
          description: ID of entry to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: entry deleted
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            text/plain:
              schema:
                type: string
  /entries/by-symbol/{symbol}:
    get:
      summary: Returns a directory entry by symbol
      operationId: getEntryBySymbol
      parameters:
        - name: symbol
          in: path
          description: Symbol of entry to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Entry response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Entry not found
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    Id:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique id
    Entry:
      type: object
      required:
        - id
        - name
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique id
        name:
          type: string
          description: Name of the institution or branch this directory entry describes
          minLength: 1
        description:
          type: string
          description: Detailed description of the entity described by this entry
          minLength: 1
        contactName:
          type: string
          description: Name of contact person
          minLength: 1
        email:
          type: string
          description: Main contact email
          minLength: 6
        symbols:
          type: array
          description: Symbols associated with this entry
          items:
            $ref: '#/components/schemas/Symbol'
        endpoints:
          type: array
          description: Service endpoints associated with this entry
          items:
            $ref: '#/components/schemas/ServiceEndpoint'
    EntryPatch:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          nullable: true
          minLength: 1
        contactName:
          type: string
          nullable: true
          minLength: 1
        email:
          type: string
          nullable: true
          minLength: 6
        symbols:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/SymbolPatch'
        endpoints:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ServiceEndpointPatch'

    SymbolProperties:
      required:
        - symbol
        - authority
      properties:
        symbol:
          type: string
          description: Uppercase string
        authority:
          type: string
          description: Uppercase string
    Symbol:
      allOf:
        - required:
          - id
          properties:
            id:
              readOnly: true
              type: string
              format: uuid
              description: Unique id
        - $ref: '#/components/schemas/SymbolProperties'
    SymbolPatch:
      allOf:
        - properties:
            id:
              type: string
              format: uuid
              description: Unique id
        - $ref: '#/components/schemas/SymbolProperties'

    ServiceEndpointProperties:
      type: object
      required:
        - name
        - type
        - address
      properties:
        name:
          type: string
        type:
          type: string
        address:
          type: string
    ServiceEndpoint:
      allOf:
        - required:
          - id
          properties:
            id:
              readOnly: true
              type: string
              format: uuid
              description: Unique id
        - $ref: '#/components/schemas/ServiceEndpointProperties'
    ServiceEndpointPatch:
      allOf:
        - properties:
            id:
              type: string
              format: uuid
              description: Unique id
        - $ref: '#/components/schemas/ServiceEndpointProperties'

    Consortium:
      type: object
      required:
        - id
        - name
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
          minLength: 1
        name:
          type: string
          description: Display name
          minLength: 1
        entry:
          type: string
          format: uuid
    ConsortiumPatch:
      type: object
      properties:
        name:
          type: string
          description: Display name
          minLength: 1
        entry:
          type: string
          format: uuid
          nullable: true
