openapi: "3.0.0"
info:
  version: 1.0.0
  title: Directoryish API
paths:
  /entries:
    get:
      summary: Returns all entries
      description: Returns all entries from the system that the user has access to.
      operationId: getEntries
      parameters:
        - name: q
          in: query
          description: keywords to filter by
          required: false
          style: form
          schema:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Entry list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entry'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Creates a new entry
      description: Creates a new entry
      operationId: addEntry
      requestBody:
        description: Entry to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEntry'
      responses:
        '200':
          description: Entry response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Id'
          links:
            GetEntryByID:
              operationId: getEntryByID
              parameters:
                id: '$response.body#/id'
            UpdateEntry:
              operationId: updateEntry
              parameters:
                id: '$response.body#/id'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /entries/{id}:
    get:
      summary: Returns a directory entry by ID
      operationId: getEntryByID
      parameters:
        - name: id
          in: path
          description: ID of entry to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Entry response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Update an entry
      description: Update an entry
      operationId: updateEntry
      parameters:
        - name: id
          in: path
          description: ID of entry to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated fields
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryPatch'
      responses:
        '204':
          description: entry updated
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: Delete directory entry by ID
      operationId: deleteEntry
      parameters:
        - name: id
          in: path
          description: ID of entry to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: entry deleted
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Id:
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          description: Unique id
    EntryRequired:
      required:
        - name
    EntryProperties:
      properties:
        name:
          type: string
          description: Name of the institution or branch this directory entry describes
          minLength: 1
        description:
          type: string
          nullable: true
          description: Detailed description of the entity described by this entry
          minLength: 1
        contact_name:
          type: string
          nullable: true
          description: Name of contact person
          minLength: 1
        email:
          type: string
          nullable: true
          description: Main contact email
          minLength: 6
        symbols:
          type: array
          description: Symbols associated with this entry
          items:
            $ref: '#/components/schemas/Symbol'
    Entry: 
      allOf: 
        - $ref: '#/components/schemas/Id'
        - $ref: '#/components/schemas/EntryProperties'
        - $ref: '#/components/schemas/EntryRequired'
    NewEntry: 
      allOf: 
        - $ref: '#/components/schemas/EntryProperties'
        - $ref: '#/components/schemas/EntryRequired'
    EntryPatch: 
      allOf: 
        - $ref: '#/components/schemas/EntryProperties'
    Symbol:
      allOf:
        - $ref: '#/components/schemas/NewSymbol'
        - required:
            - id
          properties:
            id:
              type: string
              format: uuid
              description: Unique id
    NewSymbol:
      required:
        - symbol
      properties:
        symbol:
          type: string
          description: Uppercase string
        authority:
          type: string
          description: Uppercase string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message