apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "..fullname" . }}-md
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  ModuleDescriptor: |
    {{ (.Files.Get "ModuleDescriptor-template.json") | replace "@version@" .Chart.Version | nindent 4 }}
