apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "..fullname" . }}-okapi-hook-job
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      name: {{ include "..fullname" . }}-okapi-hook-job
      labels:
        {{- include "..labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - image: "{{ .Values.okapiHooks.image.repository }}:{{ .Values.okapiHooks.image.tag }}"
        pullPolicy: {{ .Values.okapiHooks.image.pullPolicy }}
        env:
          - name: OKAPI_URL
            value: "okapi:9130"
          {{- range $k, $v := .Values.okapiHooks.env }}
          - name: {{ $k }}
            value: "{{ $v }}"
          {{- end }}
          {{- range $k, $v := .Values.okapiHooks.envSecrets }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
                name: "{{ $v.name }}"
                key: "{{ $v.key }}"
          {{- end }}
          - name: OKAPI_MD
            valueFrom:
              configMapKeyRef:
                name: {{ include "..fullname" . }}-md
                key: ModuleDescriptor
          {{- range $k, $v := .Values.okapiHooks.envConfigMaps }}
          - name: {{ $k }}
            valueFrom:
              configMapKeyRef:
                name: "{{ $v.name }}"
                key: "{{ $v.key }}"
          {{- end }}
