# Exclude everything by default
illmock/*

# Include go.mod and go.sum
!illmock/go.mod
!illmock/go.sum

# Include .go files
!illmock/**/*.go

# reqform includes xml, html
!illmock/reqform/*.xml
!illmock/reqform/*.html

# Exclude tests
illmock/test
illmock/**/*_test.go
