openapi: 3.0.0
info:
  title: Broker API
  version: 1.0.0
  description: API for retrieving broker data

components:
  parameters:
    Tenant:
      name: X-Okapi-Tenant
      in: header
      description: Okapi Tenant
      required: false
      schema:
        type: string
        pattern: '^[_a-z][_a-z0-9]*$'
    RequesterRequestId:
      name: requester_req_id
      in: query
      description: Filter Ill transactions by requester request id
      schema:
        type: string
    IllTransactionId:
      name: ill_transaction_id
      in: query
      schema:
        type: string
      description: Filter by ILL transaction ID
    RequesterSymbol:
      name: requester_symbol
      in: query
      description: Filter by requester symbol
      schema:
        type: string
    Offset:
      name: offset
      in: query
      description: Offset for pagination (first item is 0)
      schema:
        type: integer
        format: int32
    Limit:
      name: limit
      in: query
      description: Limit for pagination
      schema:
        type: integer
        format: int32
  schemas:
    Index:
      type: object
      properties:
        revision:
          type: string
          description: VCS revision
        signature:
          type: string
          description: Application signature
        links:
          type: object
          properties:
            illTransactionsLink:
              type: string
              description: Link to ILL transactions
            peersLink:
              type: string
              description: Link to peers
            eventsLink:
              type: string
              description: Link to events
            locatedSuppliersLink:
              type: string
              description: Link to located suppliers
          required:
            - eventsLink
            - illTransactionsLink
            - peersLink
            - locatedSuppliersLink
      required:
        - revision
        - signature
        - links
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
    IllTransactions:
      type: object
      required:
        - items
        - about
      properties:
        about:
          $ref: '#/components/schemas/About'
        items:
          type: array
          description: List of ILL transactions
          items:
            $ref: '#/components/schemas/IllTransaction'
    Events:
      type: object
      required:
        - items
        - about
      properties:
        about:
          $ref: '#/components/schemas/About'
        items:
          type: array
          description: List of events
          items:
            $ref: '#/components/schemas/Event'
    Peers:
      type: object
      required:
        - items
        - about
      properties:
        about:
          $ref: '#/components/schemas/About'
        items:
          type: array
          description: List of peers
          items:
            $ref: '#/components/schemas/Peer'
    LocatedSuppliers:
      type: object
      required:
        - items
        - about
      properties:
        about:
          $ref: '#/components/schemas/About'
        items:
          type: array
          description: List of peers
          items:
            $ref: '#/components/schemas/LocatedSupplier'
    About:
      type: object
      required:
        - count
      properties:
        count:
          type: integer
          format: int64
          description: Total number of items in the result
        nextLink:
          type: string
          description: Link to the next page of results
        prevLink:
          type: string
          description: Link to the previous page of results
    Event:
      type: object
      properties:
        ID:
          type: string
          description: Unique identifier of the event
        Timestamp:
          type: string
          format: date-time
          description: Timestamp of the event
        IllTransactionID:
          type: string
          description: ID of the ILL transaction (if applicable)
        EventType:
          type: string
          description: Type of the event
        EventName:
          type: string
          description: Name of the event
        EventStatus:
          type: string
          description: Status of the event
        EventData:
          type: object
          description: Data associated with the event
          additionalProperties: true
        ResultData:
          type: object
          description: Result data of the event
          additionalProperties: true
        ParentID:
          type: string
          description: Parent event ID
      required:  # List required fields if any
        - ID
        - IllTransactionID
        - Timestamp
        - EventType
        - EventName
        - EventStatus
    IllTransaction:
      type: object
      properties:
        ID:
          type: string
          description: Unique identifier for the ILL transaction
        Timestamp:
          type: string
          format: date-time
          description: Timestamp of the transaction
        RequesterSymbol:
          type: string
          description: Symbol of the requesting institution
        RequesterID:
          type: string
          description: ID of the requesting institution
        LastRequesterAction:
          type: string
          description: Last action performed by the requester
        PrevRequesterAction:
          type: string
          description: Previous action performed by the requester
        SupplierSymbol:
          type: string
          description: Symbol of the supplying institution
        RequesterRequestID:
          type: string
          description: ID of the request from the requester's side
        SupplierRequestID:
          type: string
          description: ID of the request from the supplier's side
        LastSupplierStatus:
          type: string
          description: Last status update from the supplier
        PrevSupplierStatus:
          type: string
          description: Previous status update from the supplier
        IllTransactionData:
          type: object
          description: Result data of the event
          additionalProperties: true
        EventsLink:
          type: string
          description: Link to Ill Transaction events
        LocatedSuppliersLink:
          type: string
          description: Link to located Suppliers
        RequesterPeerLink:
          type: string
          description: Link to requester Peer
      required:
        - ID
        - Timestamp
        - RequesterSymbol
        - RequesterID
        - LastRequesterAction
        - PrevRequesterAction
        - SupplierSymbol
        - RequesterRequestID
        - SupplierRequestID
        - LastSupplierStatus
        - PrevSupplierStatus
        - IllTransactionData
        - EventsLink
        - LocatedSuppliersLink
        - RequesterPeerLink
    Peer:
      type: object
      properties:
        ID:
          type: string
          description: Unique identifier for the peer
        Symbols:
          type: array
          items:
            type: string
          description: Unique symbol representing the peer
        Name:
          type: string
          description: Name of the peer
        Url:
          type: string
          description: Network URL of the peer
        RefreshPolicy:
          type: string
          enum: [never, transaction]
          description: Policy for refreshing peer information (never, transaction)
        RefreshTime:
          type: string
          format: date-time
          description: Timestamp of refresh
        LoansCount:
          type: integer
          format: int32
          description: Count of loans
        BorrowsCount:
          type: integer
          format: int32
          description: Count of borrows
        Vendor:
          type: string
          description: Vendor of the ISO18626 implementation, e.g "Alma", "ReShare"
        BrokerMode:
          type: string
          description: Broker mode, e.g "opaque" or "transparent"
        CustomData:
          type: object
          description: Custom data of peer
          additionalProperties: true
        HttpHeaders:
          type: object
          description: HTTP headers to be sent with requests to the peer
          additionalProperties:
            type: string
      required:
        - ID
        - Symbols
        - Name
        - Url
        - RefreshPolicy
        - Vendor
        - BrokerMode

    LocatedSupplier:
      type: object
      properties:
        ID:
          type: string
          description: Generate ID
        IllTransactionID:
          type: string
          description: Ill Transaction ID
        SupplierID:
          type: string
          description: Supplier ID from peer table
        SupplierSymbol:
          type: string
          description: Supplier symbol to use for communication
        Ordinal:
          type: integer
          format: int32
          description: Ordinal number for ordering
        SupplierStatus:
          type: string
          description: Supplier status, possible values (new, selected, skipped)
        PrevAction:
          type: string
          description: Previous requester action
        PrevStatus:
          type: string
          description: Previous supplier transaction status
        LastAction:
          type: string
          description: Latest requester action
        LastStatus:
          type: string
          description: Latest supplier transaction status
        LocalID:
          type: string
          description: Item local ID
        PrevReason:
          type: string
          description: Previous requester reason
        LastReason:
          type: string
          description: Latest requester reason
        SupplierRequestID:
          type: string
          description: Supplier request ID
        SupplierPeerLink:
          type: string
          description: Link to supplier Peer
      required:
        - ID
        - IllTransactionID
        - SupplierID
        - SupplierSymbol
        - Ordinal
        - SupplierPeerLink

paths:
  /:
    get:
      summary: Retrieve index information
      responses:
        '200':
          description: Successful retrieval of index information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Index'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /events:
    get:
      summary: Retrieve events
      parameters:
        - $ref: '#/components/parameters/Tenant'
        - $ref: '#/components/parameters/RequesterRequestId'
        - $ref: '#/components/parameters/IllTransactionId'
        - $ref: '#/components/parameters/RequesterSymbol'
      responses:
        '200':
          description: Successful retrieval of events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
        '400':
          description: Bad Request. Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /ill_transactions/{id}:
    get:
      summary: Get an ILL transaction by ID
      parameters:
        - $ref: '#/components/parameters/Tenant'
        - $ref: '#/components/parameters/RequesterSymbol'
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the ILL transaction to retrieve
      responses:
        '200':
          description: Successful retrieval of the ILL transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IllTransaction'
        '400':
          description: Bad Request. Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found. ILL transaction not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete an ILL transaction by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the ILL transaction to delete
      responses:
        '204':
          description: ILL transaction deleted successfully (No Content)
        '404':
          description: ILL transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /ill_transactions:
    get:
      summary: Get all ILL transactions
      parameters:
        - $ref: '#/components/parameters/Tenant'
        - $ref: '#/components/parameters/RequesterRequestId'
        - $ref: '#/components/parameters/RequesterSymbol'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Successful retrieval of the ILL transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IllTransactions'
        '400':
          description: Bad Request. Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden. Invalid tenant.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /peers:
    get:
      summary: Get all peers
      parameters:
        - in: query
          name: cql
          schema:
            type: string
          description: Filter peers by symbol
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Successful retrieval of peers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Peers'
        '400':
          description: Bad Request. Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new peer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peer'
      responses:
        '201':
          description: Peer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Peer'
        '400':
          description: Bad request (e.g., invalid data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /peers/{id}:
    get:
      summary: Get a peer by symbol
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the peer to retrieve
      responses:
        '200':
          description: Successful retrieval of the peer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Peer'
        '404':
          description: Peer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a peer
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the peer to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peer'
      responses:
        '200':
          description: Peer updated successfully
        '400':
          description: Bad request (e.g., invalid data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Peer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a peer
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the peer to delete
      responses:
        '204':
          description: Peer deleted successfully (No Content)
        '404':
          description: Peer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /located_suppliers:
    get:
      summary: Retrieve located suppliers
      parameters:
        - $ref: '#/components/parameters/Tenant'
        - $ref: '#/components/parameters/RequesterRequestId'
        - $ref: '#/components/parameters/IllTransactionId'
        - $ref: '#/components/parameters/RequesterSymbol'
      responses:
        '200':
          description: Successful retrieval of located suppliers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocatedSuppliers'
        '400':
          description: Bad Request. Invalid query parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
