openapi: "3.0.0"
info:
  version: 1.0.0
  title: Directory entries API
paths:
  /directory/entries:
    get:
      summary: Returns all entries
      description: Returns all entries from the system that the user has access to.
      operationId: getEntries
      parameters:
        - name: cql
          in: query
          description: CQL query filter
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: offset of first entry
          required: false
          schema:
            type: integer
            format: int32
        - name: peer_url
          in: query
          description: override url in result
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Entry list response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntriesResponse'
              example:
                $ref: './examples/directory.json'
        '400':
          description: Request validation error
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

# apiroadmap.yaml

components:
  schemas:
    EntriesResponse:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Entry'
        resultInfo:
          $ref: '#/components/schemas/ResultInfo'
    ResultInfo:
      type: object
      properties:
        totalRecords:
          type: integer
        diagnostics:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
    Consortium:
      type: object
      required:
        - id
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
        name:
          type: string
        entry:
          type: string
          format: uuid
    Tier:
      type: object
      required:
        - id
        - consortium
        - name
        - type
        - level
        - cost
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
        consortium:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        level:
          type: string
        cost:
          type: number
    Network:
      type: object
      required:
        - id
        - name
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
        consortium:
          type: string
          format: uuid
        name:
          type: string
        priority:
          type: integer
    Membership:
      type: object
      required:
        - consortium
        - entry
      properties:
        consortium:
          type: string
          format: uuid
        entry:
          type: string
          format: uuid
    MembershipTier:
      type: object
      required:
        - consortium
        - entry
      properties:
        membership:
          type: string
          format: uuid
        tier:
          type: string
          format: uuid
    MembershipNetwork:
      type: object
      required:
        - consortium
        - entry
      properties:
        membership:
          type: string
          format: uuid
        network:
          type: string
          format: uuid

    # Similar to existing domain
    Entry:
      type: object
      required:
        - id
        - name
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        parent:
          type: string
        description:
          type: string
        organizationId:
          type: string
        contactName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        lmsLocationCode:
          type: string
        hrid:
          type: string
        timeZone:
          type: string
        symbols:
          type: array
          items:
            $ref: '#/components/schemas/Symbol'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        closures:
          type: array
          items:
            $ref: '#/components/schemas/Closure'
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/ServiceEndpoint'
        networks:
          readOnly: true
          type: array
          items:
            $ref: '#/components/schemas/Network'
        tiers:
          readOnly: true
          type: array
          items:
            $ref: '#/components/schemas/Tier'
        lmsConfig:
          type: object
          $ref: '#/components/schemas/LmsConfig'
    LmsConfig:
      required:
        - address
        - fromAgency
      properties:
        address:
          type: string
          description: Base URL of the the LMS API
        fromAgency:
          type: string
          description: Agency code used when the entry is acting as the supplying agency
        fromAgencyAuthentication:
          type: string
          description: Authentication token or credentials for the fromAgency
        toAgency:
          type: string
          description: Agency code used when the entry is acting as the requesting agency
        lookupUserEnable:
          type: boolean
          description: Whether user lookup is enabled
          default: true
        acceptItemEnable:
          type: boolean
          description: Whether item acceptance is enabled
          default: true
        checkInItemEnable:
          type: boolean
          description: Whether item check-in is enabled
          default: true
        checkOutItemEnable:
          type: boolean
          description: Whether item check-out is enabled
          default: true
        requestItemRequestType:
          type: string
          description: For Request Item requests, the type of request to create.
          default: Page
        requestItemRequestScopeType:
          type: string
          description: For Request Item requests, the scope type of request to create.
          default: Item
        requestItemBibIdCode:
          type: string
          description: For Request Item requests, the code indicating how to interpret the bib id
          default: SYSNUMBER
        requestItemPickupLocationEnable:
          type: boolean
          description: Whether to include a pickup location when making Request Item requests
          default: true
        supplierPickupLocation:
          type: string
          description: The pickup location code to use when the entry is acting as the supplying agency
          default: ILL Office
    Symbol:
      required:
        - id
        - symbol
        - authority
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
        symbol:
          type: string
          description: Uppercase string
        authority:
          type: string
          description: Uppercase string
    Authority:
      required:
        - id
        - symbol
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique id
        symbol:
          type: string
          description: Uppercase string
    ServiceEndpoint:
      type: object
      required:
        - id
        - entry
        - name
        - type
        - address
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
        entry:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        address:
          type: string
    Address:
      type: object
      required:
        - id
        - entry
        - type
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
        entry:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - Default
            - Shipping
            - Billing
            - Other
        addressComponents:
          type: array
          items:
            $ref: '#/components/schemas/AddressComponent'
    AddressComponent:
      type: object
      required:
        - id
        - address
        - type
        - value
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
        address:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - Thoroughfare
            - Locality
            - AdministrativeArea
            - PostalCode
            - CountryCode
            - Other
        value:
          type: string
    Closure:
      type: object
      required:
        - id
        - entry
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier
        entry:
          type: string
          format: uuid
        startDate:
          type: string
          description: ISO8601 date
        endDate:
          type: string
          description: ISO8601 date
        reason:
          type: string
