// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package importdb

import (
	pr_db "github.com/indexdata/crosslink/broker/patron_request/db"
	"github.com/indexdata/crosslink/iso18626"
	"github.com/jackc/pgx/v5/pgtype"
)

type BranchSymbol struct {
	SymbolValue string
	PeerID      string
}

type IllTransaction struct {
	ID                     string
	Timestamp              pgtype.Timestamp
	RequesterSymbol        pgtype.Text
	RequesterID            pgtype.Text
	LastRequesterAction    pgtype.Text
	PrevRequesterAction    pgtype.Text
	SupplierSymbol         pgtype.Text
	RequesterRequestID     pgtype.Text
	PrevRequesterRequestID pgtype.Text
	SupplierRequestID      pgtype.Text
	LastSupplierStatus     pgtype.Text
	PrevSupplierStatus     pgtype.Text
	IllTransactionData     []byte
}

type Item struct {
	ID           string
	PrID         string
	Barcode      string
	CallNumber   pgtype.Text
	Title        pgtype.Text
	ItemID       pgtype.Text
	LmsRequestID pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type LocatedSupplier struct {
	ID                string
	IllTransactionID  string
	SupplierID        string
	SupplierSymbol    string
	Ordinal           int32
	SupplierStatus    pgtype.Text
	PrevAction        pgtype.Text
	PrevStatus        pgtype.Text
	LastAction        pgtype.Text
	LastStatus        pgtype.Text
	LocalID           pgtype.Text
	PrevReason        pgtype.Text
	LastReason        pgtype.Text
	SupplierRequestID pgtype.Text
	LocalSupplier     bool
}

type Notification struct {
	ID             string
	PrID           string
	FromSymbol     string
	ToSymbol       string
	Direction      string
	Kind           string
	Note           pgtype.Text
	Cost           pgtype.Numeric
	Currency       pgtype.Text
	Condition      pgtype.Text
	Receipt        pgtype.Text
	CreatedAt      pgtype.Timestamp
	AcknowledgedAt pgtype.Timestamp
}

type PatronRequest struct {
	ID                string
	CreatedAt         pgtype.Timestamp
	IllRequest        iso18626.Request
	State             pr_db.PatronRequestState
	Side              pr_db.PatronRequestSide
	Patron            pgtype.Text
	RequesterSymbol   pgtype.Text
	SupplierSymbol    pgtype.Text
	Tenant            pgtype.Text
	RequesterReqID    pgtype.Text
	NeedsAttention    bool
	LastAction        pgtype.Text
	LastActionOutcome pgtype.Text
	LastActionResult  pgtype.Text
	Items             []pr_db.PrItem
	Language          interface{}
	TerminalState     bool
	UpdatedAt         pgtype.Timestamp
	IllResponse       iso18626.SupplyingAgencyMessage
	InternalNote      pgtype.Text
	NextReqID         pgtype.Text
	PrevReqID         pgtype.Text
	RetryBibInfo      *iso18626.BibliographicInfo
	StateModel        string
}

type PatronRequestSearchView struct {
	ID                       string
	CreatedAt                pgtype.Timestamp
	IllRequest               []byte
	State                    string
	Side                     string
	Patron                   pgtype.Text
	RequesterSymbol          pgtype.Text
	SupplierSymbol           pgtype.Text
	Tenant                   pgtype.Text
	RequesterReqID           pgtype.Text
	NeedsAttention           bool
	LastAction               pgtype.Text
	LastActionOutcome        pgtype.Text
	LastActionResult         pgtype.Text
	Items                    []byte
	Language                 interface{}
	TerminalState            bool
	UpdatedAt                pgtype.Timestamp
	IllResponse              []byte
	InternalNote             pgtype.Text
	NextReqID                pgtype.Text
	PrevReqID                pgtype.Text
	RetryBibInfo             []byte
	StateModel               string
	HasNotification          bool
	HasCost                  bool
	HasUnreadNotification    bool
	HasInternalNote          pgtype.Bool
	ServiceType              interface{}
	ServiceLevel             interface{}
	NeededAt                 pgtype.Timestamp
	UnreadNotificationsCount int64
	RequesterName            pgtype.Text
	SupplierName             pgtype.Text
}

type Peer struct {
	ID            string
	Name          string
	RefreshPolicy string
	RefreshTime   pgtype.Timestamp
	Url           string
	LoansCount    int32
	BorrowsCount  int32
	Vendor        string
	BrokerMode    string
	CustomData    []byte
	HttpHeaders   []byte
}

type ScheduledTask struct {
	ID         string
	EventName  string
	Schedule   string
	ActionData []byte
	Title      pgtype.Text
	RunAt      pgtype.Timestamptz
	Status     string
	Owner      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Symbol struct {
	SymbolValue string
	PeerID      string
}

type Template struct {
	ID          string
	Owner       string
	Title       string
	Purpose     string
	Subject     pgtype.Text
	Body        string
	ContentType string
	Labels      []string
	Audience    pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
