// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_query.sql

package importdb

import (
	"context"

	pr_db "github.com/indexdata/crosslink/broker/patron_request/db"
	"github.com/indexdata/crosslink/iso18626"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteImportedItemsNotPresent = `-- name: DeleteImportedItemsNotPresent :exec
DELETE FROM item
WHERE pr_id = $1
  AND id <> ALL($2::text[])
`

type DeleteImportedItemsNotPresentParams struct {
	PrID string
	Ids  []string
}

func (q *Queries) DeleteImportedItemsNotPresent(ctx context.Context, db DBTX, arg DeleteImportedItemsNotPresentParams) error {
	_, err := db.Exec(ctx, deleteImportedItemsNotPresent, arg.PrID, arg.Ids)
	return err
}

const deleteImportedLocatedSuppliersNotPresent = `-- name: DeleteImportedLocatedSuppliersNotPresent :exec
DELETE FROM located_supplier
WHERE ill_transaction_id = $1
  AND id <> ALL($2::text[])
`

type DeleteImportedLocatedSuppliersNotPresentParams struct {
	IllTransactionID string
	Ids              []string
}

func (q *Queries) DeleteImportedLocatedSuppliersNotPresent(ctx context.Context, db DBTX, arg DeleteImportedLocatedSuppliersNotPresentParams) error {
	_, err := db.Exec(ctx, deleteImportedLocatedSuppliersNotPresent, arg.IllTransactionID, arg.Ids)
	return err
}

const deleteImportedNotificationsNotPresent = `-- name: DeleteImportedNotificationsNotPresent :exec
DELETE FROM notification
WHERE pr_id = $1
  AND id <> ALL($2::text[])
`

type DeleteImportedNotificationsNotPresentParams struct {
	PrID string
	Ids  []string
}

func (q *Queries) DeleteImportedNotificationsNotPresent(ctx context.Context, db DBTX, arg DeleteImportedNotificationsNotPresentParams) error {
	_, err := db.Exec(ctx, deleteImportedNotificationsNotPresent, arg.PrID, arg.Ids)
	return err
}

const getImportIllTransactionByRequesterRequestID = `-- name: GetImportIllTransactionByRequesterRequestID :one
SELECT id, requester_request_id
FROM ill_transaction
WHERE requester_request_id = $1
`

type GetImportIllTransactionByRequesterRequestIDRow struct {
	ID                 string
	RequesterRequestID pgtype.Text
}

func (q *Queries) GetImportIllTransactionByRequesterRequestID(ctx context.Context, db DBTX, requesterRequestID pgtype.Text) (GetImportIllTransactionByRequesterRequestIDRow, error) {
	row := db.QueryRow(ctx, getImportIllTransactionByRequesterRequestID, requesterRequestID)
	var i GetImportIllTransactionByRequesterRequestIDRow
	err := row.Scan(&i.ID, &i.RequesterRequestID)
	return i, err
}

const getImportItemParent = `-- name: GetImportItemParent :one
SELECT pr_id FROM item WHERE id = $1
`

func (q *Queries) GetImportItemParent(ctx context.Context, db DBTX, id string) (string, error) {
	row := db.QueryRow(ctx, getImportItemParent, id)
	var pr_id string
	err := row.Scan(&pr_id)
	return pr_id, err
}

const getImportLocatedSupplierParent = `-- name: GetImportLocatedSupplierParent :one
SELECT ill_transaction_id FROM located_supplier WHERE id = $1
`

func (q *Queries) GetImportLocatedSupplierParent(ctx context.Context, db DBTX, id string) (string, error) {
	row := db.QueryRow(ctx, getImportLocatedSupplierParent, id)
	var ill_transaction_id string
	err := row.Scan(&ill_transaction_id)
	return ill_transaction_id, err
}

const getImportNotificationParent = `-- name: GetImportNotificationParent :one
SELECT pr_id FROM notification WHERE id = $1
`

func (q *Queries) GetImportNotificationParent(ctx context.Context, db DBTX, id string) (string, error) {
	row := db.QueryRow(ctx, getImportNotificationParent, id)
	var pr_id string
	err := row.Scan(&pr_id)
	return pr_id, err
}

const lockImportBatchAction = `-- name: LockImportBatchAction :one
SELECT id, created_at
FROM scheduled_task
WHERE owner = $1
  AND title = $2
FOR UPDATE
`

type LockImportBatchActionParams struct {
	Owner string
	Title pgtype.Text
}

type LockImportBatchActionRow struct {
	ID        string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) LockImportBatchAction(ctx context.Context, db DBTX, arg LockImportBatchActionParams) (LockImportBatchActionRow, error) {
	row := db.QueryRow(ctx, lockImportBatchAction, arg.Owner, arg.Title)
	var i LockImportBatchActionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const lockImportIllTransaction = `-- name: LockImportIllTransaction :one
SELECT id, requester_request_id
FROM ill_transaction
WHERE id = $1
FOR UPDATE
`

type LockImportIllTransactionRow struct {
	ID                 string
	RequesterRequestID pgtype.Text
}

func (q *Queries) LockImportIllTransaction(ctx context.Context, db DBTX, id string) (LockImportIllTransactionRow, error) {
	row := db.QueryRow(ctx, lockImportIllTransaction, id)
	var i LockImportIllTransactionRow
	err := row.Scan(&i.ID, &i.RequesterRequestID)
	return i, err
}

const lockImportPatronRequest = `-- name: LockImportPatronRequest :one
SELECT id, requester_req_id
FROM patron_request
WHERE id = $1
FOR UPDATE
`

type LockImportPatronRequestRow struct {
	ID             string
	RequesterReqID pgtype.Text
}

func (q *Queries) LockImportPatronRequest(ctx context.Context, db DBTX, id string) (LockImportPatronRequestRow, error) {
	row := db.QueryRow(ctx, lockImportPatronRequest, id)
	var i LockImportPatronRequestRow
	err := row.Scan(&i.ID, &i.RequesterReqID)
	return i, err
}

const lockImportTemplatesByLabels = `-- name: LockImportTemplatesByLabels :many
SELECT id, created_at
FROM template
WHERE owner = $1
  AND labels && $2::text[]
ORDER BY id
FOR UPDATE
`

type LockImportTemplatesByLabelsParams struct {
	Owner  string
	Labels []string
}

type LockImportTemplatesByLabelsRow struct {
	ID        string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) LockImportTemplatesByLabels(ctx context.Context, db DBTX, arg LockImportTemplatesByLabelsParams) ([]LockImportTemplatesByLabelsRow, error) {
	rows, err := db.Query(ctx, lockImportTemplatesByLabels, arg.Owner, arg.Labels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockImportTemplatesByLabelsRow
	for rows.Next() {
		var i LockImportTemplatesByLabelsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportedPatronRequest = `-- name: UpdateImportedPatronRequest :exec
UPDATE patron_request
SET created_at = $1,
    ill_request = $2,
    state = $3,
    side = $4,
    patron = $5,
    requester_symbol = $6,
    supplier_symbol = $7,
    tenant = $8,
    requester_req_id = $9,
    needs_attention = $10,
    last_action = $11,
    last_action_outcome = $12,
    last_action_result = $13,
    items = $14,
    language = $15,
    terminal_state = $16,
    updated_at = $17,
    ill_response = $18,
    internal_note = $19,
    next_req_id = $20,
    prev_req_id = $21,
    retry_bib_info = $22,
    state_model = $23
WHERE id = $24
`

type UpdateImportedPatronRequestParams struct {
	CreatedAt         pgtype.Timestamp
	IllRequest        iso18626.Request
	State             pr_db.PatronRequestState
	Side              pr_db.PatronRequestSide
	Patron            pgtype.Text
	RequesterSymbol   pgtype.Text
	SupplierSymbol    pgtype.Text
	Tenant            pgtype.Text
	RequesterReqID    pgtype.Text
	NeedsAttention    bool
	LastAction        pgtype.Text
	LastActionOutcome pgtype.Text
	LastActionResult  pgtype.Text
	Items             []pr_db.PrItem
	Language          interface{}
	TerminalState     bool
	UpdatedAt         pgtype.Timestamp
	IllResponse       iso18626.SupplyingAgencyMessage
	InternalNote      pgtype.Text
	NextReqID         pgtype.Text
	PrevReqID         pgtype.Text
	RetryBibInfo      *iso18626.BibliographicInfo
	StateModel        string
	ID                string
}

func (q *Queries) UpdateImportedPatronRequest(ctx context.Context, db DBTX, arg UpdateImportedPatronRequestParams) error {
	_, err := db.Exec(ctx, updateImportedPatronRequest,
		arg.CreatedAt,
		arg.IllRequest,
		arg.State,
		arg.Side,
		arg.Patron,
		arg.RequesterSymbol,
		arg.SupplierSymbol,
		arg.Tenant,
		arg.RequesterReqID,
		arg.NeedsAttention,
		arg.LastAction,
		arg.LastActionOutcome,
		arg.LastActionResult,
		arg.Items,
		arg.Language,
		arg.TerminalState,
		arg.UpdatedAt,
		arg.IllResponse,
		arg.InternalNote,
		arg.NextReqID,
		arg.PrevReqID,
		arg.RetryBibInfo,
		arg.StateModel,
		arg.ID,
	)
	return err
}
