// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Authority struct {
	ID     uuid.UUID
	Symbol uuid.UUID
}

type Consortium struct {
	ID             uuid.UUID
	DirectoryEntry uuid.NullUUID
	Name           sql.NullString
}

type DirectoryEntry struct {
	ID              uuid.UUID
	Parent          uuid.NullUUID
	Name            string
	Description     sql.NullString
	LmsLocationCode sql.NullString
	ContactName     sql.NullString
	EmailAddress    sql.NullString
	PhoneNumber     sql.NullString
}

type Membership struct {
	ID          uuid.UUID
	Institution uuid.UUID
	Consortium  uuid.UUID
}

type MembershipNetwork struct {
	ID         uuid.UUID
	Membership uuid.UUID
	Network    uuid.UUID
}

type MembershipTier struct {
	ID         uuid.UUID
	Membership uuid.UUID
	Tier       uuid.UUID
}

type Network struct {
	ID   uuid.UUID
	Name sql.NullString
}

type Symbol struct {
	ID        uuid.UUID
	Owner     uuid.NullUUID
	Authority uuid.NullUUID
	Symbol    string
}

type Tier struct {
	ID   uuid.UUID
	Name sql.NullString
}
