// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Authority struct {
	ID     pgtype.UUID
	Symbol string
}

type Consortium struct {
	ID             pgtype.UUID
	DirectoryEntry pgtype.UUID
	Name           pgtype.Text
}

type DirectoryEntry struct {
	ID              pgtype.UUID
	Parent          pgtype.UUID
	Name            string
	Description     pgtype.Text
	LmsLocationCode pgtype.Text
	ContactName     pgtype.Text
	EmailAddress    pgtype.Text
	PhoneNumber     pgtype.Text
}

type Membership struct {
	ID          pgtype.UUID
	Institution pgtype.UUID
	Consortium  pgtype.UUID
}

type MembershipNetwork struct {
	ID         pgtype.UUID
	Membership pgtype.UUID
	Network    pgtype.UUID
}

type MembershipTier struct {
	ID         pgtype.UUID
	Membership pgtype.UUID
	Tier       pgtype.UUID
}

type Network struct {
	ID   pgtype.UUID
	Name pgtype.Text
}

type Symbol struct {
	ID        pgtype.UUID
	Owner     pgtype.UUID
	Authority pgtype.UUID
	Symbol    string
}

type Tier struct {
	ID   pgtype.UUID
	Name pgtype.Text
}
