// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
)

type Consortium struct {
	ID    uuid.UUID
	Entry *uuid.UUID
	Name  string
}

type Entry struct {
	ID              uuid.UUID
	Parent          *uuid.UUID
	Name            string
	Description     *string
	LmsLocationCode *string
	ContactName     *string
	Email           *string
	Phone           *string
}

type Membership struct {
	ID          uuid.UUID
	Institution uuid.UUID
	Consortium  uuid.UUID
}

type MembershipNetwork struct {
	ID         uuid.UUID
	Membership uuid.UUID
	Network    uuid.UUID
}

type MembershipTier struct {
	ID         uuid.UUID
	Membership uuid.UUID
	Tier       uuid.UUID
}

type Network struct {
	ID   uuid.UUID
	Name *string
}

type ServiceEndpoint struct {
	ID      uuid.UUID
	Entry   uuid.UUID
	Name    string
	Type    string
	Address string
}

type Symbol struct {
	ID        uuid.UUID
	Owner     uuid.UUID
	Authority string
	Symbol    string
}

type Tier struct {
	ID   uuid.UUID
	Name *string
}
