// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authorityBySymbol = `-- name: AuthorityBySymbol :one
SELECT id, symbol FROM authorities
WHERE symbol = $1 LIMIT 1
`

func (q *Queries) AuthorityBySymbol(ctx context.Context, symbol string) (Authority, error) {
	row := q.db.QueryRow(ctx, authorityBySymbol, symbol)
	var i Authority
	err := row.Scan(&i.ID, &i.Symbol)
	return i, err
}

const createAuthority = `-- name: CreateAuthority :one
INSERT INTO authorities (
  symbol
) VALUES (
  $1
)
RETURNING id, symbol
`

func (q *Queries) CreateAuthority(ctx context.Context, symbol string) (Authority, error) {
	row := q.db.QueryRow(ctx, createAuthority, symbol)
	var i Authority
	err := row.Scan(&i.ID, &i.Symbol)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  name, contact_name, email
) VALUES (
  $1, $2, $3
)
RETURNING id, parent, name, description, lms_location_code, contact_name, email, phone
`

type CreateEntryParams struct {
	Name        string
	ContactName pgtype.Text
	Email       pgtype.Text
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry, arg.Name, arg.ContactName, arg.Email)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Description,
		&i.LmsLocationCode,
		&i.ContactName,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const createSymbol = `-- name: CreateSymbol :one
INSERT INTO symbols (
  owner, symbol, authority
) VALUES (
  $1, $2, $3
)
RETURNING id, owner, authority, symbol
`

type CreateSymbolParams struct {
	Owner     uuid.UUID
	Symbol    string
	Authority uuid.UUID
}

func (q *Queries) CreateSymbol(ctx context.Context, arg CreateSymbolParams) (Symbol, error) {
	row := q.db.QueryRow(ctx, createSymbol, arg.Owner, arg.Symbol, arg.Authority)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Authority,
		&i.Symbol,
	)
	return i, err
}

const entryById = `-- name: EntryById :one
SELECT id, parent, name, description, lms_location_code, contact_name, email, phone FROM entries
WHERE id = $1 LIMIT 1
`

func (q *Queries) EntryById(ctx context.Context, id uuid.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, entryById, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Description,
		&i.LmsLocationCode,
		&i.ContactName,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const listAuthorities = `-- name: ListAuthorities :many
SELECT id, symbol FROM authorities
`

func (q *Queries) ListAuthorities(ctx context.Context) ([]Authority, error) {
	rows, err := q.db.Query(ctx, listAuthorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Authority
	for rows.Next() {
		var i Authority
		if err := rows.Scan(&i.ID, &i.Symbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT e.id, e.parent, e.name, e.description, e.lms_location_code, e.contact_name, e.email, e.phone, s.id, s.owner, s.authority, s.symbol
FROM entries e
LEFT JOIN entrysymbols s ON e.id = s.owner
ORDER BY e.name, e.id
`

type ListEntriesRow struct {
	Entry       Entry
	Entrysymbol Entrysymbol
}

func (q *Queries) ListEntries(ctx context.Context) ([]ListEntriesRow, error) {
	rows, err := q.db.Query(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.Entry.ID,
			&i.Entry.Parent,
			&i.Entry.Name,
			&i.Entry.Description,
			&i.Entry.LmsLocationCode,
			&i.Entry.ContactName,
			&i.Entry.Email,
			&i.Entry.Phone,
			&i.Entrysymbol.ID,
			&i.Entrysymbol.Owner,
			&i.Entrysymbol.Authority,
			&i.Entrysymbol.Symbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET
  name = coalesce($1, name),
  contact_name = coalesce($2, CASE WHEN NOT $3::bool THEN contact_name END),
  email = coalesce($4, CASE WHEN NOT $5::bool THEN email END)
WHERE id = $6
`

type UpdateEntryParams struct {
	Name           pgtype.Text
	ContactName    pgtype.Text
	DelContactName bool
	Email          pgtype.Text
	DelEmail       bool
	ID             uuid.UUID
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.Exec(ctx, updateEntry,
		arg.Name,
		arg.ContactName,
		arg.DelContactName,
		arg.Email,
		arg.DelEmail,
		arg.ID,
	)
	return err
}
