//go:build go1.22

// Package importoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package importoapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/indexdata/crosslink/broker/events"
	"github.com/indexdata/crosslink/broker/ill_db"
	dirapi "github.com/indexdata/crosslink/directory/api"
	"github.com/indexdata/crosslink/iso18626"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ActionCapabilityKind.
const (
	Operation  ActionCapabilityKind = "operation"
	Transition ActionCapabilityKind = "transition"
)

// Valid indicates whether the value is a known member of the ActionCapabilityKind enum.
func (e ActionCapabilityKind) Valid() bool {
	switch e {
	case Operation:
		return true
	case Transition:
		return true
	default:
		return false
	}
}

// Defines values for BatchActionName.
const (
	EmailPullslips BatchActionName = "email-pullslips"
	RequestAging   BatchActionName = "request-aging"
)

// Valid indicates whether the value is a known member of the BatchActionName enum.
func (e BatchActionName) Valid() bool {
	switch e {
	case EmailPullslips:
		return true
	case RequestAging:
		return true
	default:
		return false
	}
}

// Defines values for ConflictPolicy.
const (
	Fail   ConflictPolicy = "fail"
	Skip   ConflictPolicy = "skip"
	Update ConflictPolicy = "update"
)

// Valid indicates whether the value is a known member of the ConflictPolicy enum.
func (e ConflictPolicy) Valid() bool {
	switch e {
	case Fail:
		return true
	case Skip:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for ImportItemType.
const (
	ImportItemTypeBatchAction   ImportItemType = "batchAction"
	ImportItemTypePatronRequest ImportItemType = "patronRequest"
	ImportItemTypeTemplate      ImportItemType = "template"
)

// Valid indicates whether the value is a known member of the ImportItemType enum.
func (e ImportItemType) Valid() bool {
	switch e {
	case ImportItemTypeBatchAction:
		return true
	case ImportItemTypePatronRequest:
		return true
	case ImportItemTypeTemplate:
		return true
	default:
		return false
	}
}

// Defines values for ImportLocatedSupplierSupplierStatus.
const (
	New      ImportLocatedSupplierSupplierStatus = "new"
	Selected ImportLocatedSupplierSupplierStatus = "selected"
	Skipped  ImportLocatedSupplierSupplierStatus = "skipped"
)

// Valid indicates whether the value is a known member of the ImportLocatedSupplierSupplierStatus enum.
func (e ImportLocatedSupplierSupplierStatus) Valid() bool {
	switch e {
	case New:
		return true
	case Selected:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for ImportPatronRequestNotificationDirection.
const (
	Received ImportPatronRequestNotificationDirection = "received"
	Sent     ImportPatronRequestNotificationDirection = "sent"
)

// Valid indicates whether the value is a known member of the ImportPatronRequestNotificationDirection enum.
func (e ImportPatronRequestNotificationDirection) Valid() bool {
	switch e {
	case Received:
		return true
	case Sent:
		return true
	default:
		return false
	}
}

// Defines values for ImportPatronRequestNotificationKind.
const (
	ImportPatronRequestNotificationKindCondition ImportPatronRequestNotificationKind = "condition"
	ImportPatronRequestNotificationKindNote      ImportPatronRequestNotificationKind = "note"
)

// Valid indicates whether the value is a known member of the ImportPatronRequestNotificationKind enum.
func (e ImportPatronRequestNotificationKind) Valid() bool {
	switch e {
	case ImportPatronRequestNotificationKindCondition:
		return true
	case ImportPatronRequestNotificationKindNote:
		return true
	default:
		return false
	}
}

// Defines values for ModelActionParamsSendTo.
const (
	ModelActionParamsSendToPatron ModelActionParamsSendTo = "patron"
	ModelActionParamsSendToStaff  ModelActionParamsSendTo = "staff"
)

// Valid indicates whether the value is a known member of the ModelActionParamsSendTo enum.
func (e ModelActionParamsSendTo) Valid() bool {
	switch e {
	case ModelActionParamsSendToPatron:
		return true
	case ModelActionParamsSendToStaff:
		return true
	default:
		return false
	}
}

// Defines values for ModelActionTrigger.
const (
	Auto   ModelActionTrigger = "auto"
	Manual ModelActionTrigger = "manual"
)

// Valid indicates whether the value is a known member of the ModelActionTrigger enum.
func (e ModelActionTrigger) Valid() bool {
	switch e {
	case Auto:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for ModelStateSide.
const (
	REQUESTER ModelStateSide = "REQUESTER"
	SUPPLIER  ModelStateSide = "SUPPLIER"
)

// Valid indicates whether the value is a known member of the ModelStateSide enum.
func (e ModelStateSide) Valid() bool {
	switch e {
	case REQUESTER:
		return true
	case SUPPLIER:
		return true
	default:
		return false
	}
}

// Defines values for PeerBrokerMode.
const (
	Opaque      PeerBrokerMode = "opaque"
	Translucent PeerBrokerMode = "translucent"
	Transparent PeerBrokerMode = "transparent"
)

// Valid indicates whether the value is a known member of the PeerBrokerMode enum.
func (e PeerBrokerMode) Valid() bool {
	switch e {
	case Opaque:
		return true
	case Translucent:
		return true
	case Transparent:
		return true
	default:
		return false
	}
}

// Defines values for PeerRefreshPolicy.
const (
	Never       PeerRefreshPolicy = "never"
	Transaction PeerRefreshPolicy = "transaction"
)

// Valid indicates whether the value is a known member of the PeerRefreshPolicy enum.
func (e PeerRefreshPolicy) Valid() bool {
	switch e {
	case Never:
		return true
	case Transaction:
		return true
	default:
		return false
	}
}

// Defines values for PrNotificationKind.
const (
	PrNotificationKindCondition PrNotificationKind = "condition"
	PrNotificationKindNote      PrNotificationKind = "note"
)

// Valid indicates whether the value is a known member of the PrNotificationKind enum.
func (e PrNotificationKind) Valid() bool {
	switch e {
	case PrNotificationKindCondition:
		return true
	case PrNotificationKindNote:
		return true
	default:
		return false
	}
}

// Defines values for PullSlipType.
const (
	Batch  PullSlipType = "batch"
	Single PullSlipType = "single"
)

// Valid indicates whether the value is a known member of the PullSlipType enum.
func (e PullSlipType) Valid() bool {
	switch e {
	case Batch:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for StateModelType.
const (
	StateModelTypeStateModel StateModelType = "StateModel"
)

// Valid indicates whether the value is a known member of the StateModelType enum.
func (e StateModelType) Valid() bool {
	switch e {
	case StateModelTypeStateModel:
		return true
	default:
		return false
	}
}

// Defines values for StateModelServiceType.
const (
	Copy       StateModelServiceType = "Copy"
	CopyOrLoan StateModelServiceType = "CopyOrLoan"
	Loan       StateModelServiceType = "Loan"
)

// Valid indicates whether the value is a known member of the StateModelServiceType enum.
func (e StateModelServiceType) Valid() bool {
	switch e {
	case Copy:
		return true
	case CopyOrLoan:
		return true
	case Loan:
		return true
	default:
		return false
	}
}

// Defines values for TemplateAudience.
const (
	TemplateAudiencePatron TemplateAudience = "patron"
	TemplateAudienceStaff  TemplateAudience = "staff"
)

// Valid indicates whether the value is a known member of the TemplateAudience enum.
func (e TemplateAudience) Valid() bool {
	switch e {
	case TemplateAudiencePatron:
		return true
	case TemplateAudienceStaff:
		return true
	default:
		return false
	}
}

// Defines values for TemplateContentType.
const (
	Html TemplateContentType = "html"
	Text TemplateContentType = "text"
)

// Valid indicates whether the value is a known member of the TemplateContentType enum.
func (e TemplateContentType) Valid() bool {
	switch e {
	case Html:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for TemplatePurpose.
const (
	Email    TemplatePurpose = "email"
	Pullslip TemplatePurpose = "pullslip"
)

// Valid indicates whether the value is a known member of the TemplatePurpose enum.
func (e TemplatePurpose) Valid() bool {
	switch e {
	case Email:
		return true
	case Pullslip:
		return true
	default:
		return false
	}
}

// Defines values for UpdateNotificationReceiptReceipt.
const (
	ACCEPTED     UpdateNotificationReceiptReceipt = "ACCEPTED"
	FAILEDTOSEND UpdateNotificationReceiptReceipt = "FAILED_TO_SEND"
	REJECTED     UpdateNotificationReceiptReceipt = "REJECTED"
	SEEN         UpdateNotificationReceiptReceipt = "SEEN"
	SENT         UpdateNotificationReceiptReceipt = "SENT"
)

// Valid indicates whether the value is a known member of the UpdateNotificationReceiptReceipt enum.
func (e UpdateNotificationReceiptReceipt) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case FAILEDTOSEND:
		return true
	case REJECTED:
		return true
	case SEEN:
		return true
	case SENT:
		return true
	default:
		return false
	}
}

// Defines values for NotificationKind.
const (
	NotificationKindCondition NotificationKind = "condition"
	NotificationKindNote      NotificationKind = "note"
)

// Valid indicates whether the value is a known member of the NotificationKind enum.
func (e NotificationKind) Valid() bool {
	switch e {
	case NotificationKindCondition:
		return true
	case NotificationKindNote:
		return true
	default:
		return false
	}
}

// About defines model for About.
type About struct {
	// Count Total number of items in the result
	Count int64 `json:"count"`

	// FirstLink Link to the first page of results
	FirstLink *string `json:"firstLink,omitempty"`

	// LastLink Link to the last page of results
	LastLink *string `json:"lastLink,omitempty"`

	// NextLink Link to the next page of results
	NextLink *string `json:"nextLink,omitempty"`

	// PrevLink Link to the previous page of results
	PrevLink *string `json:"prevLink,omitempty"`
}

// AboutWithFacets defines model for AboutWithFacets.
type AboutWithFacets struct {
	// Count Total number of items in the result
	Count int64 `json:"count"`

	// Facets List of facets for the result
	Facets *FacetsResult `json:"facets,omitempty"`

	// FirstLink Link to the first page of results
	FirstLink *string `json:"firstLink,omitempty"`

	// LastLink Link to the last page of results
	LastLink *string `json:"lastLink,omitempty"`

	// NextLink Link to the next page of results
	NextLink *string `json:"nextLink,omitempty"`

	// PrevLink Link to the previous page of results
	PrevLink *string `json:"prevLink,omitempty"`
}

// ActionCapability Definition of an action supported by the broker, including its execution kind and accepted parameters.
type ActionCapability struct {
	// Kind How the action is executed. Operation actions invoke built-in domain logic; transition actions immediately succeed using the state model's configured success transition.
	Kind *ActionCapabilityKind `json:"kind,omitempty"`

	// Name Name of the action
	Name string `json:"name"`

	// Parameters List of parameter names for this action
	Parameters []string `json:"parameters"`
}

// ActionCapabilityKind How the action is executed. Operation actions invoke built-in domain logic; transition actions immediately succeed using the state model's configured success transition.
type ActionCapabilityKind string

// ActionResult defines model for ActionResult.
type ActionResult struct {
	// FromState State before action execution
	FromState string `json:"fromState"`

	// Message Action message
	Message *string `json:"message,omitempty"`

	// Outcome Action outcome ("success", "failure", "review")
	Outcome string `json:"outcome"`

	// Result Action result
	Result string `json:"result"`

	// ToState State after action execution
	ToState *string `json:"toState,omitempty"`
}

// AllowedAction defines model for AllowedAction.
type AllowedAction struct {
	// Available Indicates if this action is available for execution in the current state
	Available bool `json:"available"`

	// Name Name of the action
	Name string `json:"name"`

	// Parameters List of parameters for this action
	Parameters []string `json:"parameters"`

	// Primary Indicates if this action is primary action for the state
	Primary *bool `json:"primary,omitempty"`
}

// AllowedActions defines model for AllowedActions.
type AllowedActions struct {
	Actions []AllowedAction `json:"actions"`
}

// AppliesTo Criteria determining whether a state, action, or event applies to a request. When omitted, the element applies to all requests.
type AppliesTo struct {
	// ServiceTypes ISO 18626 service types for which this element applies
	ServiceTypes []StateModelServiceType `json:"serviceTypes"`
}

// BatchAction A scheduled batch action
type BatchAction struct {
	// ActionName Name of the batch action to run
	ActionName BatchActionName `json:"actionName"`

	// ActionParams Parameters for the batch action. For request-aging, interval is required and must be a Go duration string such as "24h" or "168h". Additional parameters are passed to the generated patron-request background action.
	ActionParams *map[string]interface{} `json:"actionParams,omitempty"`

	// Active Indicates if the batch action is active
	Active bool `json:"active"`

	// BatchQuery Batch action selection query in CQL format
	BatchQuery string `json:"batchQuery"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// EventsLink Link to execution events for this batch action
	EventsLink string `json:"eventsLink"`

	// Id Unique identifier of the batch action
	Id string `json:"id"`

	// NextRun Next execution time according to the schedule
	NextRun *time.Time `json:"nextRun,omitempty"`

	// Owner Symbol of the institution that owns the batch action. Empty for unrestricted actions created with master access.
	Owner string `json:"owner"`

	// Schedule RRULE schedule expression, e.g. "FREQ=WEEKLY;BYDAY=MO;BYHOUR=6;BYMINUTE=0" (every Monday at 06:00)
	Schedule string `json:"schedule"`

	// Title Title of the batch action, for display purposes
	Title *string `json:"title,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// BatchActionDefault A built-in batch action that clients can offer as a starting point
type BatchActionDefault struct {
	// ActionName Name of the batch action to run
	ActionName BatchActionName `json:"actionName"`

	// ActionParams Parameters for the batch action. For request-aging, interval is required and must be a Go duration string such as "24h" or "168h". Additional parameters are passed to the generated patron-request background action.
	ActionParams *map[string]interface{} `json:"actionParams,omitempty"`

	// BatchQuery Batch action selection query in CQL format
	BatchQuery string `json:"batchQuery"`

	// Schedule RRULE schedule expression, e.g. "FREQ=WEEKLY;BYDAY=MO;BYHOUR=6;BYMINUTE=0" (every Monday at 06:00)
	Schedule string `json:"schedule"`

	// Title Title of the batch action, for display purposes
	Title *string `json:"title,omitempty"`

	// TitleKey Stable identifier for this default, for clients to look up a localized title
	TitleKey string `json:"titleKey"`
}

// BatchActionName Name of the batch action to run
type BatchActionName string

// BatchActions defines model for BatchActions.
type BatchActions struct {
	About About `json:"about"`

	// Items List of batch actions
	Items []BatchAction `json:"items"`
}

// BibliographicInfo Bibliographic information for an ILL request item, as defined in ISO18626
type BibliographicInfo = map[string]interface{}

// ConflictPolicy defines model for ConflictPolicy.
type ConflictPolicy string

// CreateBatchAction Request body for creating a batch action
type CreateBatchAction struct {
	// ActionName Name of the batch action to run
	ActionName BatchActionName `json:"actionName"`

	// ActionParams Parameters for the batch action. For request-aging, interval is required and must be a Go duration string such as "24h" or "168h". Additional parameters are passed to the generated patron-request background action.
	ActionParams *map[string]interface{} `json:"actionParams,omitempty"`

	// BatchQuery Batch action selection query in CQL format
	BatchQuery string `json:"batchQuery"`

	// Schedule RRULE schedule expression, e.g. "FREQ=WEEKLY;BYDAY=MO;BYHOUR=6;BYMINUTE=0" (every Monday at 06:00)
	Schedule string `json:"schedule"`

	// Title Title of the batch action, for display purposes
	Title *string `json:"title,omitempty"`
}

// CreatePatronRequest defines model for CreatePatronRequest.
type CreatePatronRequest struct {
	// Id Unique identifier of the patron request
	Id *string `json:"id,omitempty"`

	// IllRequest JSON of ISO18626 request
	IllRequest map[string]interface{} `json:"illRequest"`

	// InternalNote Staff-only internal note, local to this request and never shared with peers
	InternalNote *string `json:"internalNote,omitempty"`

	// Patron User who requested item
	Patron *string `json:"patron,omitempty"`

	// RequesterSymbol Requester symbol
	RequesterSymbol *string `json:"requesterSymbol,omitempty"`
}

// CreatePrNotification Create patron request notification body
type CreatePrNotification struct {
	// Note Note of notification
	Note string `json:"note"`
}

// CreatePullSlip Create pull slip body. If both illTransactionIds and cql are provided, illTransactionIds will be used for pull slip generation and cql will be ignored.
type CreatePullSlip struct {
	// Cql CQL search for patron requests to create pull slips for
	Cql *string `json:"cql,omitempty"`

	// IllTransactionIds Patron request IDs to create pull slips for
	IllTransactionIds *[]string `json:"illTransactionIds,omitempty"`
}

// CreateTemplate Request body for creating a template
type CreateTemplate struct {
	// Audience Intended audience for the template. Omit to apply to both patron and staff.
	Audience *TemplateAudience `json:"audience,omitempty"`

	// Body Body of the email or pull slip template. Supports {{.X}} placeholders. For full list of supported placeholders, see the Template object.
	Body string `json:"body"`

	// ContentType Output content type for the template body
	ContentType TemplateContentType `json:"contentType"`

	// Labels Labels identifying the template's usage context
	Labels []string `json:"labels"`

	// Purpose Purpose of the template
	Purpose TemplatePurpose `json:"purpose"`

	// Subject Subject line template, supports {{.X}} placeholders. Not used for pullslip templates. For full list of supported placeholders, see the Template object.
	Subject *string `json:"subject,omitempty"`

	// Title Human-readable title for the template
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error *string `json:"error,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// EventData Data associated with the event
	EventData *events.EventData `json:"eventData,omitempty"`

	// EventName Name of the event
	EventName string `json:"eventName"`

	// EventStatus Status of the event
	EventStatus string `json:"eventStatus"`

	// EventType Type of the event
	EventType string `json:"eventType"`

	// Id Unique identifier of the event
	Id string `json:"id"`

	// IllTransactionID ID of the ILL transaction (if applicable)
	IllTransactionID string `json:"illTransactionID"`

	// ParentID Parent event ID
	ParentID *string `json:"parentID,omitempty"`

	// PatronRequestID ID of the Patron request (if applicable)
	PatronRequestID *string `json:"patronRequestID,omitempty"`

	// ResultData Result data of the event
	ResultData *events.EventResult `json:"resultData,omitempty"`

	// Timestamp Timestamp of the event
	Timestamp time.Time `json:"timestamp"`
}

// Events defines model for Events.
type Events struct {
	About About `json:"about"`

	// Items List of events
	Items []Event `json:"items"`
}

// ExecuteAction defines model for ExecuteAction.
type ExecuteAction struct {
	// Action Action to execute
	Action string `json:"action"`

	// ActionParams Action parameters
	ActionParams *map[string]interface{} `json:"actionParams,omitempty"`
}

// FacetResultValue defines model for FacetResultValue.
type FacetResultValue struct {
	// Count Count of items for this facet value
	Count int64 `json:"count"`

	// Label Human-readable name for the facet value, when one is available. Omitted when the value has no associated name.
	Label *string `json:"label,omitempty"`

	// Value Facet value
	Value string `json:"value"`
}

// FacetsResult List of facets for the result
type FacetsResult = []struct {
	// Name Facet name
	Name string `json:"name"`

	// Values List of facet values. At most 100 entries are returned.
	Values []FacetResultValue `json:"values"`
}

// IllTransaction defines model for IllTransaction.
type IllTransaction struct {
	// EventsLink Link to Ill Transaction events
	EventsLink string `json:"eventsLink"`

	// Id Unique identifier for the ILL transaction
	Id string `json:"id"`

	// IllTransactionData Result data of the event
	IllTransactionData ill_db.IllTransactionData `json:"illTransactionData"`

	// LastRequesterAction Last action performed by the requester
	LastRequesterAction string `json:"lastRequesterAction"`

	// LastSupplierStatus Last status update from the supplier
	LastSupplierStatus string `json:"lastSupplierStatus"`

	// LocatedSuppliersLink Link to located Suppliers
	LocatedSuppliersLink string `json:"locatedSuppliersLink"`

	// PrevRequesterAction Previous action performed by the requester
	PrevRequesterAction string `json:"prevRequesterAction"`

	// PrevSupplierStatus Previous status update from the supplier
	PrevSupplierStatus string `json:"prevSupplierStatus"`

	// RequesterID ID of the requesting institution
	RequesterID string `json:"requesterID"`

	// RequesterPeerLink Link to requester Peer
	RequesterPeerLink string `json:"requesterPeerLink"`

	// RequesterRequestID ID of the request from the requester's side
	RequesterRequestID string `json:"requesterRequestID"`

	// RequesterSymbol Symbol of the requesting institution
	RequesterSymbol string `json:"requesterSymbol"`

	// SupplierRequestID ID of the request from the supplier's side
	SupplierRequestID string `json:"supplierRequestID"`

	// SupplierSymbol Symbol of the supplying institution
	SupplierSymbol string `json:"supplierSymbol"`

	// Timestamp Timestamp of the transaction
	Timestamp time.Time `json:"timestamp"`
}

// IllTransactions defines model for IllTransactions.
type IllTransactions struct {
	About About `json:"about"`

	// Items List of ILL transactions
	Items []IllTransaction `json:"items"`
}

// ImportIllTransaction defines model for ImportIllTransaction.
type ImportIllTransaction struct {
	Id                     string                    `json:"id"`
	IllTransactionData     ill_db.IllTransactionData `json:"illTransactionData"`
	LastRequesterAction    *string                   `json:"lastRequesterAction,omitempty"`
	LastSupplierStatus     *string                   `json:"lastSupplierStatus,omitempty"`
	PrevRequesterAction    *string                   `json:"prevRequesterAction,omitempty"`
	PrevRequesterRequestID *string                   `json:"prevRequesterRequestID,omitempty"`
	PrevSupplierStatus     *string                   `json:"prevSupplierStatus,omitempty"`
	RequesterRequestID     string                    `json:"requesterRequestID"`
	RequesterSymbol        string                    `json:"requesterSymbol"`
	SupplierRequestID      *string                   `json:"supplierRequestID,omitempty"`
	SupplierSymbol         *string                   `json:"supplierSymbol,omitempty"`
	Timestamp              time.Time                 `json:"timestamp"`
}

// ImportItemError defines model for ImportItemError.
type ImportItemError struct {
	Error      string  `json:"error"`
	Identifier *string `json:"identifier,omitempty"`

	// Line One-based NDJSON record number.
	Line  int32           `json:"line"`
	Owner *string         `json:"owner,omitempty"`
	Type  *ImportItemType `json:"type,omitempty"`
}

// ImportItemType defines model for ImportItemType.
type ImportItemType string

// ImportLocatedSupplier defines model for ImportLocatedSupplier.
type ImportLocatedSupplier struct {
	Id                string                               `json:"id"`
	LastAction        *string                              `json:"lastAction,omitempty"`
	LastReason        *string                              `json:"lastReason,omitempty"`
	LastStatus        *string                              `json:"lastStatus,omitempty"`
	LocalID           *string                              `json:"localID,omitempty"`
	LocalSupplier     bool                                 `json:"localSupplier"`
	Ordinal           int32                                `json:"ordinal"`
	PrevAction        *string                              `json:"prevAction,omitempty"`
	PrevReason        *string                              `json:"prevReason,omitempty"`
	PrevStatus        *string                              `json:"prevStatus,omitempty"`
	SupplierRequestID *string                              `json:"supplierRequestID,omitempty"`
	SupplierStatus    *ImportLocatedSupplierSupplierStatus `json:"supplierStatus,omitempty"`
	SupplierSymbol    string                               `json:"supplierSymbol"`
}

// ImportLocatedSupplierSupplierStatus defines model for ImportLocatedSupplier.SupplierStatus.
type ImportLocatedSupplierSupplierStatus string

// ImportPatronRequest defines model for ImportPatronRequest.
type ImportPatronRequest struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// IllRequest JSON of ISO18626 request
	IllRequest iso18626.Request `json:"illRequest"`

	// IllResponse JSON of ISO18626 supplying agency message
	IllResponse        *iso18626.SupplyingAgencyMessage `json:"illResponse,omitempty"`
	InternalNote       *string                          `json:"internalNote,omitempty"`
	LastAction         *string                          `json:"lastAction,omitempty"`
	LastActionOutcome  *string                          `json:"lastActionOutcome,omitempty"`
	LastActionResult   *string                          `json:"lastActionResult,omitempty"`
	NeedsAttention     bool                             `json:"needsAttention"`
	NextReqId          *string                          `json:"nextReqId,omitempty"`
	Patron             *string                          `json:"patron,omitempty"`
	PrevReqId          *string                          `json:"prevReqId,omitempty"`
	RequesterRequestId string                           `json:"requesterRequestId"`
	RequesterSymbol    string                           `json:"requesterSymbol"`

	// RetryBibInfo Bibliographic retry information as defined in ISO18626
	RetryBibInfo   *iso18626.BibliographicInfo `json:"retryBibInfo,omitempty"`
	Side           string                      `json:"side"`
	State          string                      `json:"state"`
	StateModel     string                      `json:"stateModel"`
	SupplierSymbol *string                     `json:"supplierSymbol,omitempty"`
	UpdatedAt      time.Time                   `json:"updatedAt"`
}

// ImportPatronRequestBundle defines model for ImportPatronRequestBundle.
type ImportPatronRequestBundle struct {
	IllTransaction   *ImportIllTransaction             `json:"illTransaction,omitempty"`
	Items            []ImportPatronRequestItem         `json:"items"`
	LocatedSuppliers []ImportLocatedSupplier           `json:"locatedSuppliers"`
	Notifications    []ImportPatronRequestNotification `json:"notifications"`
	PatronRequest    ImportPatronRequest               `json:"patronRequest"`
}

// ImportPatronRequestItem defines model for ImportPatronRequestItem.
type ImportPatronRequestItem struct {
	Barcode      string    `json:"barcode"`
	CallNumber   *string   `json:"callNumber,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	ItemId       *string   `json:"itemId,omitempty"`
	LmsRequestId *string   `json:"lmsRequestId,omitempty"`
	Title        *string   `json:"title,omitempty"`
}

// ImportPatronRequestNotification defines model for ImportPatronRequestNotification.
type ImportPatronRequestNotification struct {
	AcknowledgedAt *time.Time                               `json:"acknowledgedAt,omitempty"`
	Condition      *string                                  `json:"condition,omitempty"`
	Cost           *float64                                 `json:"cost,omitempty"`
	CreatedAt      time.Time                                `json:"createdAt"`
	Currency       *string                                  `json:"currency,omitempty"`
	Direction      ImportPatronRequestNotificationDirection `json:"direction"`
	FromSymbol     string                                   `json:"fromSymbol"`
	Id             string                                   `json:"id"`
	Kind           ImportPatronRequestNotificationKind      `json:"kind"`
	Note           *string                                  `json:"note,omitempty"`
	Receipt        *string                                  `json:"receipt,omitempty"`
	ToSymbol       string                                   `json:"toSymbol"`
}

// ImportPatronRequestNotificationDirection defines model for ImportPatronRequestNotification.Direction.
type ImportPatronRequestNotificationDirection string

// ImportPatronRequestNotificationKind defines model for ImportPatronRequestNotification.Kind.
type ImportPatronRequestNotificationKind string

// ImportResourceRecord defines model for ImportResourceRecord.
type ImportResourceRecord struct {
	// Data Resource data to import.
	Data ImportResourceRecord_Data `json:"data"`

	// Owner Symbol of the owning institution
	Owner string         `json:"owner"`
	Type  ImportItemType `json:"type"`
}

// ImportResourceRecord_Data Resource data to import.
type ImportResourceRecord_Data struct {
	union json.RawMessage
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	BatchActions   ImportSectionResult `json:"batchActions"`
	Errors         []ImportItemError   `json:"errors"`
	PatronRequests ImportSectionResult `json:"patronRequests"`
	Templates      ImportSectionResult `json:"templates"`
}

// ImportSectionResult defines model for ImportSectionResult.
type ImportSectionResult struct {
	Failed   int32 `json:"failed"`
	Imported int32 `json:"imported"`
	Skipped  int32 `json:"skipped"`
}

// Index defines model for Index.
type Index struct {
	Links struct {
		// BatchActionsLink Link to batch actions
		BatchActionsLink string `json:"batchActionsLink"`

		// BorrowingRequestsLink Link to borrowing requests
		BorrowingRequestsLink string `json:"borrowingRequestsLink"`

		// IllTransactionsLink Link to ILL transactions
		IllTransactionsLink string `json:"illTransactionsLink"`

		// LendingRequestsLink Link to lending requests
		LendingRequestsLink string `json:"lendingRequestsLink"`

		// PeersLink Link to peers
		PeersLink string `json:"peersLink"`
	} `json:"links"`

	// Revision VCS revision
	Revision string `json:"revision"`

	// Signature Application signature
	Signature string `json:"signature"`
}

// LocatedSupplier defines model for LocatedSupplier.
type LocatedSupplier struct {
	// Id Generate ID
	Id string `json:"id"`

	// IllTransactionID Ill Transaction ID
	IllTransactionID string `json:"illTransactionID"`

	// LastAction Latest requester action
	LastAction *string `json:"lastAction,omitempty"`

	// LastReason Latest requester reason
	LastReason *string `json:"lastReason,omitempty"`

	// LastStatus Latest supplier transaction status
	LastStatus *string `json:"lastStatus,omitempty"`

	// LocalID Item local ID
	LocalID *string `json:"localID,omitempty"`

	// Ordinal Ordinal number for ordering
	Ordinal int32 `json:"ordinal"`

	// PrevAction Previous requester action
	PrevAction *string `json:"prevAction,omitempty"`

	// PrevReason Previous requester reason
	PrevReason *string `json:"prevReason,omitempty"`

	// PrevStatus Previous supplier transaction status
	PrevStatus *string `json:"prevStatus,omitempty"`

	// SupplierID Supplier ID from peer table
	SupplierID string `json:"supplierID"`

	// SupplierPeerLink Link to supplier Peer
	SupplierPeerLink string `json:"supplierPeerLink"`

	// SupplierRequestID Supplier request ID
	SupplierRequestID *string `json:"supplierRequestID,omitempty"`

	// SupplierStatus Supplier status, possible values (new, selected, skipped)
	SupplierStatus *string `json:"supplierStatus,omitempty"`

	// SupplierSymbol Supplier symbol to use for communication
	SupplierSymbol string `json:"supplierSymbol"`
}

// LocatedSuppliers defines model for LocatedSuppliers.
type LocatedSuppliers struct {
	About About `json:"about"`

	// Items List of peers
	Items []LocatedSupplier `json:"items"`
}

// ModelAction Declares an action available while in this state.
type ModelAction struct {
	// AppliesTo Criteria determining whether a state, action, or event applies to a request. When omitted, the element applies to all requests.
	AppliesTo *AppliesTo `json:"appliesTo,omitempty"`

	// Desc Description of the action
	Desc *string `json:"desc,omitempty"`

	// Name Name of the action
	Name string `json:"name"`

	// Params Parameters for the action. The presence of parameters indicates that the action requires additional input to be executed.
	Params *ModelAction_Params `json:"params,omitempty"`

	// PrimaryFor Makes this the primary action for the selected service types. At most one applicable action may be primary for a service type in a state.
	PrimaryFor *AppliesTo `json:"primaryFor,omitempty"`

	// Transitions Action outcome to state transition mapping. When no transition is defined, the action is considered to be non-state-changing.
	Transitions *struct {
		// Failure Target state when the action fails.
		Failure *string `json:"failure,omitempty"`

		// Review Target state when the action requires review.
		Review *string `json:"review,omitempty"`

		// Success Target state when the action succeeds.
		Success *string `json:"success,omitempty"`
	} `json:"transitions,omitempty"`

	// Trigger Trigger for the action
	Trigger *ModelActionTrigger `json:"trigger,omitempty"`
}

// ModelActionParamsSendTo defines model for ModelAction.Params.SendTo.
type ModelActionParamsSendTo string

// ModelAction_Params Parameters for the action. The presence of parameters indicates that the action requires additional input to be executed.
type ModelAction_Params struct {
	// SendTo Notification recipients for this action.
	SendTo *[]ModelActionParamsSendTo `json:"sendTo,omitempty"`

	// TemplateLabel Template label for this action. The template selector is used to select the appropriate template for generating messages.
	TemplateLabel        *string                `json:"templateLabel,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ModelActionTrigger Trigger for the action
type ModelActionTrigger string

// ModelEvent Declares an event considered for transition while in this state.
type ModelEvent struct {
	// AppliesTo Criteria determining whether a state, action, or event applies to a request. When omitted, the element applies to all requests.
	AppliesTo *AppliesTo `json:"appliesTo,omitempty"`

	// Desc Description of the event
	Desc *string `json:"desc,omitempty"`

	// Name Name of the event
	Name string `json:"name"`

	// Transition State transition after event has occurred. When no transition is defined, the event is considered to be non-state-changing.
	Transition *string `json:"transition,omitempty"`
}

// ModelState Definition of a particular state
type ModelState struct {
	// Actions List of all actions that may be performed on the request when in this state
	Actions *[]ModelAction `json:"actions,omitempty"`

	// AppliesTo Criteria determining whether a state, action, or event applies to a request. When omitted, the element applies to all requests.
	AppliesTo *AppliesTo `json:"appliesTo,omitempty"`

	// ClosingAction Name of the closing action for this state. Must be one of the actions defined in the actions array.
	ClosingAction *string `json:"closingAction,omitempty"`

	// Desc Description of the state, e.g., what situation is modelled by the state
	Desc *string `json:"desc,omitempty"`

	// Display Human-readable state name
	Display *string `json:"display,omitempty"`

	// Editable Indicates that a patron request can be updated in this state
	Editable *bool `json:"editable,omitempty"`

	// Events List of all events that may be triggered to the request when in this state
	Events *[]ModelEvent `json:"events,omitempty"`

	// Initial Indicates if the state is the initial state of the request
	Initial *bool `json:"initial,omitempty"`

	// ManualClose Indicates that this terminal state is the target for manual termination
	ManualClose *bool `json:"manualClose,omitempty"`

	// Name Name of the state, in capital letters with underscores
	Name string `json:"name"`

	// NeedsAttention Indicates that this state requires user attention (e.g. displayed as a flag in the UI)
	NeedsAttention *bool `json:"needsAttention,omitempty"`

	// PrimaryAction Name of the unconditional primary action for this state. Must be one of the actions defined in the actions array. Use primaryFor on individual actions when the primary action varies by service type.
	PrimaryAction *string `json:"primaryAction,omitempty"`

	// Side Indicates which side of the request the state belongs to
	Side ModelStateSide `json:"side"`

	// Terminal Indicates if the state is terminal (meaning no actions or events are allowed in this state)
	Terminal *bool `json:"terminal,omitempty"`
	union    json.RawMessage
}

// ModelStateSide Indicates which side of the request the state belongs to
type ModelStateSide string

// ModelState0 defines model for ModelState.0.
type ModelState0 struct {
	union json.RawMessage
}

// ModelState00 defines model for ModelState.0.0.
type ModelState00 = interface{}

// ModelState01 defines model for ModelState.0.1.
type ModelState01 = interface{}

// ModelState1 defines model for ModelState.1.
type ModelState1 = interface{}

// PatronRequest defines model for PatronRequest.
type PatronRequest struct {
	// AvailableActionsLink Link to available actions for this patron request
	AvailableActionsLink *string `json:"availableActionsLink,omitempty"`

	// CreatedAt Timestamp of the patron request creation
	CreatedAt time.Time `json:"createdAt"`

	// EventsLink Link to events for this patron request
	EventsLink *string `json:"eventsLink,omitempty"`

	// HasCost Indicates if the request has a cost notification
	HasCost bool `json:"hasCost"`

	// Id Unique identifier of the patron request
	Id string `json:"id"`

	// IllRequest JSON of ISO18626 request
	IllRequest map[string]interface{} `json:"illRequest"`

	// IllResponse JSON of ISO18626 supplying agency message
	IllResponse *map[string]interface{} `json:"illResponse,omitempty"`

	// IllTransactionLink Link to related ILL transaction lookup
	IllTransactionLink *string `json:"illTransactionLink,omitempty"`

	// InternalNote Staff-only internal note, local to this request and never shared with peers
	InternalNote *string `json:"internalNote,omitempty"`

	// Items List of patron request items
	Items *[]PrItem `json:"items,omitempty"`

	// ItemsLink Link to items for this patron request
	ItemsLink *string `json:"itemsLink,omitempty"`

	// LastAction Latest action on this request
	LastAction *string `json:"lastAction,omitempty"`

	// LastActionOutcome Latest action outcome
	LastActionOutcome *string `json:"lastActionOutcome,omitempty"`

	// LastActionResult Latest action status ("NEW", "PROCESSING", "SUCCESS", "PROBLEM", "ERROR")
	LastActionResult *string `json:"lastActionResult,omitempty"`

	// NeedsAttention Indicates if the request needs attention
	NeedsAttention bool `json:"needsAttention"`

	// NextReqId ID of the next patron request in the sequence
	NextReqId *string `json:"nextReqId,omitempty"`

	// NotificationsLink Link to notifications for this patron request
	NotificationsLink *string `json:"notificationsLink,omitempty"`

	// Patron User who requested item
	Patron *string `json:"patron,omitempty"`

	// PrevReqId ID of the previous patron request in the sequence
	PrevReqId *string `json:"prevReqId,omitempty"`

	// RequesterName Name of the requester peer
	RequesterName *string `json:"requesterName,omitempty"`

	// RequesterRequestId Requester patron request ID
	RequesterRequestId *string `json:"requesterRequestId,omitempty"`

	// RequesterSymbol Requester symbol
	RequesterSymbol *string `json:"requesterSymbol,omitempty"`

	// RetryBibInfo Bibliographic information for an ILL request item, as defined in ISO18626
	RetryBibInfo *BibliographicInfo `json:"retryBibInfo,omitempty"`

	// Side Patron request side - borrowing or lending
	Side string `json:"side"`

	// State Patron request state
	State string `json:"state"`

	// StateModel State model configuration key governing this request
	StateModel string `json:"stateModel"`

	// SupplierName Name of the supplier peer
	SupplierName *string `json:"supplierName,omitempty"`

	// SupplierSymbol Supplier symbol
	SupplierSymbol *string `json:"supplierSymbol,omitempty"`

	// TerminalState Indicates if the request is in terminal state
	TerminalState bool `json:"terminalState"`

	// UnreadNotificationsCount Number of unread notifications for this request
	UnreadNotificationsCount int64 `json:"unreadNotificationsCount"`

	// UpdatedAt Timestamp of the patron request last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// PatronRequests defines model for PatronRequests.
type PatronRequests struct {
	About AboutWithFacets `json:"about"`

	// Items List of patron request
	Items []PatronRequest `json:"items"`
}

// Peer defines model for Peer.
type Peer struct {
	// BorrowsCount Count of borrows
	BorrowsCount *int32 `json:"borrowsCount,omitempty"`

	// BranchSymbols Symbols of peer branches
	BranchSymbols *[]string `json:"branchSymbols,omitempty"`

	// BrokerMode Broker mode, e.g "opaque", "transparent" or "translucent"
	BrokerMode PeerBrokerMode `json:"brokerMode"`

	// CustomData Custom data of peer
	CustomData *dirapi.Entry `json:"customData,omitempty"`

	// HttpHeaders HTTP headers to be sent with requests to the peer
	HttpHeaders *map[string]string `json:"httpHeaders,omitempty"`

	// Id Unique identifier for the peer
	Id string `json:"id"`

	// LoansCount Count of loans
	LoansCount *int32 `json:"loansCount,omitempty"`

	// Name Name of the peer
	Name string `json:"name"`

	// RefreshPolicy Policy for refreshing peer information (never, transaction)
	RefreshPolicy PeerRefreshPolicy `json:"refreshPolicy"`

	// RefreshTime Timestamp of refresh
	RefreshTime *time.Time `json:"refreshTime,omitempty"`

	// Symbols Unique symbol representing the peer
	Symbols []string `json:"symbols"`

	// Url Network URL of the peer
	Url string `json:"url"`

	// Vendor Vendor of the ISO18626 implementation, e.g "Alma", "ReShare"
	Vendor string `json:"vendor"`
}

// PeerBrokerMode Broker mode, e.g "opaque", "transparent" or "translucent"
type PeerBrokerMode string

// PeerRefreshPolicy Policy for refreshing peer information (never, transaction)
type PeerRefreshPolicy string

// Peers defines model for Peers.
type Peers struct {
	About About `json:"about"`

	// Items List of peers
	Items []Peer `json:"items"`
}

// PrItem Patron request item
type PrItem struct {
	// Barcode Item barcode
	Barcode string `json:"barcode"`

	// CallNumber Item call number
	CallNumber *string `json:"callNumber,omitempty"`

	// CreatedAt Item creation date time
	CreatedAt time.Time `json:"createdAt"`

	// Id Item system id
	Id string `json:"id"`

	// ItemId Item item id
	ItemId *string `json:"itemId,omitempty"`

	// Title Item title
	Title *string `json:"title,omitempty"`
}

// PrItems defines model for PrItems.
type PrItems struct {
	About About `json:"about"`

	// Items List of patron request items
	Items []PrItem `json:"items"`
}

// PrNotification Patron request notification
type PrNotification struct {
	// AcknowledgedAt Notification acknowledged at date time
	AcknowledgedAt *time.Time `json:"acknowledgedAt,omitempty"`

	// Condition Condition of notification
	Condition *string `json:"condition,omitempty"`

	// Cost Cost amount
	Cost *float64 `json:"cost,omitempty"`

	// CreatedAt Notification creation date time
	CreatedAt time.Time `json:"createdAt"`

	// Currency Currency symbol
	Currency *string `json:"currency,omitempty"`

	// Direction Direction of the notification, either sent or received
	Direction string `json:"direction"`

	// FromSymbol Symbol of notification sender
	FromSymbol string `json:"fromSymbol"`

	// Id Notification id
	Id string `json:"id"`

	// Kind Kind of notification, either note or condition
	Kind PrNotificationKind `json:"kind"`

	// Note Note of notification
	Note *string `json:"note,omitempty"`

	// Receipt Receipt of notification
	Receipt *string `json:"receipt,omitempty"`

	// ToSymbol Symbol of notification receiver
	ToSymbol string `json:"toSymbol"`
}

// PrNotificationKind Kind of notification, either note or condition
type PrNotificationKind string

// PrNotifications defines model for PrNotifications.
type PrNotifications struct {
	About About `json:"about"`

	// Items List of patron request notifications
	Items []PrNotification `json:"items"`
}

// PullSlip A generated pull slip record
type PullSlip struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// GeneratedAt When the PDF was generated
	GeneratedAt *time.Time `json:"generatedAt,omitempty"`

	// Id Pull slip ID
	Id string `json:"id"`

	// Owner Symbol of the owning institution
	Owner string `json:"owner"`

	// PdfLink Link to download the PDF
	PdfLink *string `json:"pdfLink,omitempty"`

	// SearchCriteria Criteria used to generate this pull slip
	SearchCriteria string `json:"searchCriteria"`

	// Type Pull slip type (single, batch)
	Type PullSlipType `json:"type"`
}

// PullSlipType Pull slip type (single, batch)
type PullSlipType string

// SseResult defines model for SseResult.
type SseResult struct {
	// Data Data of the event, for example ISO18626 message
	Data map[string]interface{} `json:"data"`

	// Event Event name, for example 'message-supplier'
	Event string `json:"event"`
}

// StateModel ReShare state model definition
type StateModel struct {
	// Desc Description of the state model
	Desc *string `json:"desc,omitempty"`

	// Name Name of the state model
	Name string `json:"name"`

	// PullslipPdfTemplateLabel Template label used to resolve the PDF pullslip template for this state model.
	PullslipPdfTemplateLabel *string `json:"pullslipPdfTemplateLabel,omitempty"`

	// Selector Criteria used to select this state model for an ISO 18626 request
	Selector *StateModelSelector `json:"selector,omitempty"`

	// States A list of all allowed states
	States []ModelState `json:"states"`

	// Type Self-referential type
	Type StateModelType `json:"type"`

	// Version Version of the state model in SemVer
	Version string `json:"version"`
}

// StateModelType Self-referential type
type StateModelType string

// StateModelCapabilities Built-in states, actions and message events supported by the broker
type StateModelCapabilities struct {
	RequesterActions       []ActionCapability `json:"requesterActions"`
	RequesterMessageEvents []string           `json:"requesterMessageEvents"`
	RequesterStates        []string           `json:"requesterStates"`
	SupplierActions        []ActionCapability `json:"supplierActions"`
	SupplierMessageEvents  []string           `json:"supplierMessageEvents"`
	SupplierStates         []string           `json:"supplierStates"`
}

// StateModelSelector Criteria used to select this state model for an ISO 18626 request
type StateModelSelector struct {
	// ServiceType ISO 18626 service types handled by this state model
	ServiceType []StateModelServiceType `json:"serviceType"`
}

// StateModelServiceType ISO 18626 service type used by state-model selection and applicability rules
type StateModelServiceType string

// StatusMessage defines model for StatusMessage.
type StatusMessage struct {
	// Status Process status
	Status string `json:"status"`
}

// Template An email or pull slip template with optional placeholder support
type Template struct {
	// Audience Intended audience for the template. Omit to apply to both patron and staff.
	Audience *TemplateAudience `json:"audience,omitempty"`

	// Body Body of the email or pull slip template. Supports {{.X}} placeholders. Supported placeholders for patron request templates include {{.ReqId}}, {{.PickupLocation}}, {{.Title}}, {{.Author}}, {{.DueDate}}, {{.ReturnAddress}}, {{.BarcodeBase64}}, {{.ServiceType}}, {{.ServiceLevel}}, {{.SystemIdentifier}}, {{.Publisher}}, {{.Volume}}, {{.Issue}}, {{.Pages}}, {{.StaffNotes}}, {{.CallNumber}}, {{.LoanConditions}}, {{.PatronName}}, {{.PatronSurname}}, {{.PatronId}} and batch templates include {{.FullCount}}, {{.ActualCount}}, {{.BatchQuery}}.
	Body string `json:"body"`

	// ContentType Output content type for the template body
	ContentType TemplateContentType `json:"contentType"`

	// CreatedAt Timestamp when the template was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier of the template
	Id string `json:"id"`

	// Labels Predefined labels identifying the template's usage context. Values correspond to templateLabel parameters used in state model send-email actions.
	Labels []string `json:"labels"`

	// Purpose Purpose of the template
	Purpose TemplatePurpose `json:"purpose"`

	// Subject Subject line template, supports {{.X}} placeholders. Not used for pullslip templates. Supports same placeholders as template body.
	Subject *string `json:"subject,omitempty"`

	// Title Human-readable title for the template
	Title string `json:"title"`

	// UpdatedAt Timestamp when the template was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// TemplateAudience Intended audience for the template. Omit to apply to both patron and staff.
type TemplateAudience string

// TemplateContentType Output content type for the template body
type TemplateContentType string

// TemplatePurpose Purpose of the template
type TemplatePurpose string

// Templates defines model for Templates.
type Templates struct {
	About About `json:"about"`

	// Items List of templates
	Items []Template `json:"items"`
}

// UpdateBatchAction Request body for updating a batch action
type UpdateBatchAction struct {
	// ActionParams Parameters for the batch action
	ActionParams *map[string]interface{} `json:"actionParams,omitempty"`

	// BatchQuery Batch action selection query in CQL format
	BatchQuery string `json:"batchQuery"`

	// Schedule RRULE schedule expression, e.g. "FREQ=WEEKLY;BYDAY=MO;BYHOUR=6;BYMINUTE=0" (every Monday at 06:00)
	Schedule string `json:"schedule"`

	// Title Title of the batch action, for display purposes
	Title *string `json:"title,omitempty"`
}

// UpdateInternalNote defines model for UpdateInternalNote.
type UpdateInternalNote struct {
	// InternalNote Staff-only internal note text. Send an empty string or omit to clear the note.
	InternalNote *string `json:"internalNote,omitempty"`
}

// UpdateNotificationReceipt Update notification receipt body
type UpdateNotificationReceipt struct {
	// Receipt Notification receipt status
	Receipt UpdateNotificationReceiptReceipt `json:"receipt"`
}

// UpdateNotificationReceiptReceipt Notification receipt status
type UpdateNotificationReceiptReceipt string

// UpdateTemplate Request body for replacing a template's mutable fields.
type UpdateTemplate struct {
	// Audience Intended audience for the template. Omit to apply to both patron and staff.
	Audience *TemplateAudience `json:"audience,omitempty"`

	// Body Body of the email or pull slip template. Supports {{.X}} placeholders. For full list of supported placeholders, see the Template object.
	Body string `json:"body"`

	// ContentType Output content type for the template body
	ContentType TemplateContentType `json:"contentType"`

	// Labels Labels identifying the template's usage context
	Labels []string `json:"labels"`

	// Subject Subject line template supporting {{.X}} placeholders. Not used for pull slip templates. Omit to clear. For full list of supported placeholders, see the Template object.
	Subject *string `json:"subject,omitempty"`

	// Title Human-readable title for the template
	Title string `json:"title"`
}

// ArchiveDelay defines model for ArchiveDelay.
type ArchiveDelay = string

// ArchiveStatus defines model for ArchiveStatus.
type ArchiveStatus = string

// Cql defines model for Cql.
type Cql = string

// Facets defines model for Facets.
type Facets = []string

// IllTransactionId defines model for IllTransactionId.
type IllTransactionId = string

// Limit defines model for Limit.
type Limit = int32

// NotificationKind defines model for NotificationKind.
type NotificationKind string

// Offset defines model for Offset.
type Offset = int32

// PatronRequestId defines model for PatronRequestId.
type PatronRequestId = string

// RequesterRequestId defines model for RequesterRequestId.
type RequesterRequestId = string

// RequesterSymbol defines model for RequesterSymbol.
type RequesterSymbol = string

// Side defines model for Side.
type Side = string

// Symbol defines model for Symbol.
type Symbol = string

// Tenant defines model for Tenant.
type Tenant = string

// PostImportParams defines parameters for PostImport.
type PostImportParams struct {
	// ConflictPolicy How to handle an existing resource identity.
	ConflictPolicy *ConflictPolicy `form:"conflictPolicy,omitempty" json:"conflictPolicy,omitempty"`
}

// Getter for additional properties for ModelAction_Params. Returns the specified
// element and whether it was found
func (a ModelAction_Params) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ModelAction_Params
func (a *ModelAction_Params) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ModelAction_Params to handle AdditionalProperties
func (a *ModelAction_Params) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["sendTo"]; found {
		err = json.Unmarshal(raw, &a.SendTo)
		if err != nil {
			return fmt.Errorf("error reading 'sendTo': %w", err)
		}
		delete(object, "sendTo")
	}

	if raw, found := object["templateLabel"]; found {
		err = json.Unmarshal(raw, &a.TemplateLabel)
		if err != nil {
			return fmt.Errorf("error reading 'templateLabel': %w", err)
		}
		delete(object, "templateLabel")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ModelAction_Params to handle AdditionalProperties
func (a ModelAction_Params) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.SendTo != nil {
		object["sendTo"], err = json.Marshal(a.SendTo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sendTo': %w", err)
		}
	}

	if a.TemplateLabel != nil {
		object["templateLabel"], err = json.Marshal(a.TemplateLabel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'templateLabel': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsImportPatronRequestBundle returns the union data inside the ImportResourceRecord_Data as a ImportPatronRequestBundle
func (t ImportResourceRecord_Data) AsImportPatronRequestBundle() (ImportPatronRequestBundle, error) {
	var body ImportPatronRequestBundle
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImportPatronRequestBundle overwrites any union data inside the ImportResourceRecord_Data as the provided ImportPatronRequestBundle
func (t *ImportResourceRecord_Data) FromImportPatronRequestBundle(v ImportPatronRequestBundle) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImportPatronRequestBundle performs a merge with any union data inside the ImportResourceRecord_Data, using the provided ImportPatronRequestBundle
func (t *ImportResourceRecord_Data) MergeImportPatronRequestBundle(v ImportPatronRequestBundle) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateBatchAction returns the union data inside the ImportResourceRecord_Data as a CreateBatchAction
func (t ImportResourceRecord_Data) AsCreateBatchAction() (CreateBatchAction, error) {
	var body CreateBatchAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateBatchAction overwrites any union data inside the ImportResourceRecord_Data as the provided CreateBatchAction
func (t *ImportResourceRecord_Data) FromCreateBatchAction(v CreateBatchAction) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateBatchAction performs a merge with any union data inside the ImportResourceRecord_Data, using the provided CreateBatchAction
func (t *ImportResourceRecord_Data) MergeCreateBatchAction(v CreateBatchAction) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateTemplate returns the union data inside the ImportResourceRecord_Data as a CreateTemplate
func (t ImportResourceRecord_Data) AsCreateTemplate() (CreateTemplate, error) {
	var body CreateTemplate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateTemplate overwrites any union data inside the ImportResourceRecord_Data as the provided CreateTemplate
func (t *ImportResourceRecord_Data) FromCreateTemplate(v CreateTemplate) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateTemplate performs a merge with any union data inside the ImportResourceRecord_Data, using the provided CreateTemplate
func (t *ImportResourceRecord_Data) MergeCreateTemplate(v CreateTemplate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ImportResourceRecord_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ImportResourceRecord_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsModelState0 returns the union data inside the ModelState as a ModelState0
func (t ModelState) AsModelState0() (ModelState0, error) {
	var body ModelState0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModelState0 overwrites any union data inside the ModelState as the provided ModelState0
func (t *ModelState) FromModelState0(v ModelState0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModelState0 performs a merge with any union data inside the ModelState, using the provided ModelState0
func (t *ModelState) MergeModelState0(v ModelState0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsModelState1 returns the union data inside the ModelState as a ModelState1
func (t ModelState) AsModelState1() (ModelState1, error) {
	var body ModelState1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModelState1 overwrites any union data inside the ModelState as the provided ModelState1
func (t *ModelState) FromModelState1(v ModelState1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModelState1 performs a merge with any union data inside the ModelState, using the provided ModelState1
func (t *ModelState) MergeModelState1(v ModelState1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ModelState) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Actions != nil {
		object["actions"], err = json.Marshal(t.Actions)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'actions': %w", err)
		}
	}

	if t.AppliesTo != nil {
		object["appliesTo"], err = json.Marshal(t.AppliesTo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appliesTo': %w", err)
		}
	}

	if t.ClosingAction != nil {
		object["closingAction"], err = json.Marshal(t.ClosingAction)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'closingAction': %w", err)
		}
	}

	if t.Desc != nil {
		object["desc"], err = json.Marshal(t.Desc)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'desc': %w", err)
		}
	}

	if t.Display != nil {
		object["display"], err = json.Marshal(t.Display)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'display': %w", err)
		}
	}

	if t.Editable != nil {
		object["editable"], err = json.Marshal(t.Editable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'editable': %w", err)
		}
	}

	if t.Events != nil {
		object["events"], err = json.Marshal(t.Events)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'events': %w", err)
		}
	}

	if t.Initial != nil {
		object["initial"], err = json.Marshal(t.Initial)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'initial': %w", err)
		}
	}

	if t.ManualClose != nil {
		object["manualClose"], err = json.Marshal(t.ManualClose)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'manualClose': %w", err)
		}
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if t.NeedsAttention != nil {
		object["needsAttention"], err = json.Marshal(t.NeedsAttention)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'needsAttention': %w", err)
		}
	}

	if t.PrimaryAction != nil {
		object["primaryAction"], err = json.Marshal(t.PrimaryAction)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'primaryAction': %w", err)
		}
	}

	object["side"], err = json.Marshal(t.Side)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'side': %w", err)
	}

	if t.Terminal != nil {
		object["terminal"], err = json.Marshal(t.Terminal)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'terminal': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *ModelState) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["actions"]; found {
		err = json.Unmarshal(raw, &t.Actions)
		if err != nil {
			return fmt.Errorf("error reading 'actions': %w", err)
		}
	}

	if raw, found := object["appliesTo"]; found {
		err = json.Unmarshal(raw, &t.AppliesTo)
		if err != nil {
			return fmt.Errorf("error reading 'appliesTo': %w", err)
		}
	}

	if raw, found := object["closingAction"]; found {
		err = json.Unmarshal(raw, &t.ClosingAction)
		if err != nil {
			return fmt.Errorf("error reading 'closingAction': %w", err)
		}
	}

	if raw, found := object["desc"]; found {
		err = json.Unmarshal(raw, &t.Desc)
		if err != nil {
			return fmt.Errorf("error reading 'desc': %w", err)
		}
	}

	if raw, found := object["display"]; found {
		err = json.Unmarshal(raw, &t.Display)
		if err != nil {
			return fmt.Errorf("error reading 'display': %w", err)
		}
	}

	if raw, found := object["editable"]; found {
		err = json.Unmarshal(raw, &t.Editable)
		if err != nil {
			return fmt.Errorf("error reading 'editable': %w", err)
		}
	}

	if raw, found := object["events"]; found {
		err = json.Unmarshal(raw, &t.Events)
		if err != nil {
			return fmt.Errorf("error reading 'events': %w", err)
		}
	}

	if raw, found := object["initial"]; found {
		err = json.Unmarshal(raw, &t.Initial)
		if err != nil {
			return fmt.Errorf("error reading 'initial': %w", err)
		}
	}

	if raw, found := object["manualClose"]; found {
		err = json.Unmarshal(raw, &t.ManualClose)
		if err != nil {
			return fmt.Errorf("error reading 'manualClose': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["needsAttention"]; found {
		err = json.Unmarshal(raw, &t.NeedsAttention)
		if err != nil {
			return fmt.Errorf("error reading 'needsAttention': %w", err)
		}
	}

	if raw, found := object["primaryAction"]; found {
		err = json.Unmarshal(raw, &t.PrimaryAction)
		if err != nil {
			return fmt.Errorf("error reading 'primaryAction': %w", err)
		}
	}

	if raw, found := object["side"]; found {
		err = json.Unmarshal(raw, &t.Side)
		if err != nil {
			return fmt.Errorf("error reading 'side': %w", err)
		}
	}

	if raw, found := object["terminal"]; found {
		err = json.Unmarshal(raw, &t.Terminal)
		if err != nil {
			return fmt.Errorf("error reading 'terminal': %w", err)
		}
	}

	return err
}

// AsModelState00 returns the union data inside the ModelState0 as a ModelState00
func (t ModelState0) AsModelState00() (ModelState00, error) {
	var body ModelState00
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModelState00 overwrites any union data inside the ModelState0 as the provided ModelState00
func (t *ModelState0) FromModelState00(v ModelState00) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModelState00 performs a merge with any union data inside the ModelState0, using the provided ModelState00
func (t *ModelState0) MergeModelState00(v ModelState00) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsModelState01 returns the union data inside the ModelState0 as a ModelState01
func (t ModelState0) AsModelState01() (ModelState01, error) {
	var body ModelState01
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModelState01 overwrites any union data inside the ModelState0 as the provided ModelState01
func (t *ModelState0) FromModelState01(v ModelState01) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModelState01 performs a merge with any union data inside the ModelState0, using the provided ModelState01
func (t *ModelState0) MergeModelState01(v ModelState01) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ModelState0) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ModelState0) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostImport Import resources from NDJSON
	// (POST /import)
	PostImport(w http.ResponseWriter, r *http.Request, params PostImportParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostImport operation middleware
func (siw *ServerInterfaceWrapper) PostImport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostImportParams

	// ------------- Optional query parameter "conflictPolicy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "conflictPolicy", r.URL.Query(), &params.ConflictPolicy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "conflictPolicy"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conflictPolicy", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostImport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/import", wrapper.PostImport)

	return m
}
