linters:
  default: all
  enable:
    - whitespace
    - gosec

linters-settings:
  gosec:
    excludes:
      - G114
  errcheck:
    check-type-assertions: true # Recommended setting to enable type assertion checks
    exclude-functions:
      - (net.Listener).Close
      - (net/http.ResponseWriter).Write

run:
  timeout: "5m"

formatters:
  - gofmt