version: '3.8'
name: broker-test
services:
  postgres:
    image: postgres:latest
    container_name: crosslink_postgres
    environment:
      POSTGRES_USER: crosslink
      POSTGRES_PASSWORD: crosslink
      POSTGRES_DB: crosslink
    ports:
      - "35432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  ill_mock_sup:
    build:
      context: ./../illmock
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "19083:8080"
    environment:
      HTTP_PORT: 8080
      SUPPLIER: true