version: '3.8'
name: broker-test
services:
  ill_mock:
    build:
      context: ./..
      dockerfile: ./illmock/Dockerfile
    container_name: test_ill_mock
    ports:
      - "19083:8080"
    environment:
      HTTP_PORT: 8080
      PEER_URL: "http://${HOST_DOCKER_INTERNAL:-host.docker.internal}:19082"
