version: '3.8'
name: broker-test
services:
  postgres:
    image: postgres:latest
    container_name: test_crosslink_postgres
    environment:
      POSTGRES_USER: crosslink
      POSTGRES_PASSWORD: crosslink
      POSTGRES_DB: crosslink
    ports:
      - "35432:5432"
  ill_mock_sup:
    build:
      context: ./..
      dockerfile: ./illmock/Dockerfile
    container_name: test_ill_mock
    depends_on:
      - postgres
    ports:
      - "19083:8080"
    environment:
      HTTP_PORT: 8080
      PEER_URL: "${PEER_URL:-http://host.docker.internal:19082}"

