// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID    uuid.UUID
	Entry uuid.UUID
	Type  string
}

type AddressComponent struct {
	ID      uuid.UUID
	Address uuid.UUID
	Seq     int32
	Type    string
	Value   string
}

type Closure struct {
	ID        uuid.UUID
	Entry     uuid.UUID
	StartDate pgtype.Timestamp
	EndDate   pgtype.Timestamp
	Reason    string
}

type Entry struct {
	ID                 uuid.UUID
	Parent             *uuid.UUID
	Name               string
	Type               string
	Description        *string
	OrganizationID     *string
	ContactName        *string
	FromEmail          *string
	Tenant             *string
	Vendor             *string
	PhoneNumber        *string
	LmsLocationCode    *string
	LenderOfLastResort []string
	Hrid               *string
	TimeZone           *string
}

type EntryNetwork struct {
	ID      uuid.UUID
	Entry   uuid.UUID
	Network uuid.UUID
}

type EntryTier struct {
	ID    uuid.UUID
	Entry uuid.UUID
	Tier  uuid.UUID
}

type HoldingsConfig struct {
	ID                                   uuid.UUID
	Entry                                uuid.UUID
	MetadataUpdateMode                   *string
	SruAddress                           *string
	SruRecordSchema                      *string
	ZoomAddress                          *string
	ZoomOptionMockRecords                *string
	ZoomOptionPreferredRecordSyntax      *string
	ZoomOptionCount                      *string
	ZoomOptionElementSetName             *string
	ZoomOptionSchema                     *string
	ZoomOptionAuthentication             *string
	ZoomOptionUser                       *string
	ZoomOptionPassword                   *string
	ZoomOptionAdapterError               *string
	ZoomOptionLookupError                *string
	ZoomOptionLocation                   *string
	QueryType                            *string
	QueryIdentifier                      *string
	QueryIsbn                            *string
	QueryIssn                            *string
	QueryTitle                           *string
	HoldingsMarcCallNumberSubfield       *string
	HoldingsMarcItemIDSubfield           *string
	HoldingsMarcLocationSubfield         *string
	HoldingsMarcMainField                *string
	HoldingsMarcRestrictedSubfield       *string
	HoldingsMarcShelvingLocationSubfield *string
	HoldingsMarc21plus1Enabled           *bool
	HoldingsOpacEnabled                  *bool
	HoldingsReservoirEnabled             *bool
	MetadataMarc21Author                 *string
	MetadataMarc21Edition                *string
	MetadataMarc21Identifier             *string
	MetadataMarc21Isbn                   *string
	MetadataMarc21Issn                   *string
	MetadataMarc21Subtitle               *string
	MetadataMarc21Title                  *string
}

type LmsConfig struct {
	ID                               uuid.UUID
	Entry                            uuid.UUID
	Address                          string
	FromAgency                       string
	FromAgencyAuthentication         *string
	ToAgency                         *string
	LookupUserEnabled                *bool
	AcceptItemEnabled                *bool
	CheckinItemEnabled               *bool
	CheckoutItemEnabled              *bool
	ItemLocation                     *string
	RequestItemRequestType           *string
	RequestItemScopeType             *string
	RequestItemBibCode               *string
	RequestItemPickupLocationEnabled *bool
	RequesterPickupLocation          *string
	SupplierPickupLocation           *string
	RequesterPatronPattern           *string
}

type Network struct {
	ID         uuid.UUID
	Consortium uuid.UUID
	Name       *string
	Priority   float64
	Reciprocal *bool
}

type ServiceEndpoint struct {
	ID      uuid.UUID
	Entry   uuid.UUID
	Name    string
	Type    string
	Address string
}

type Symbol struct {
	ID        uuid.UUID
	Owner     uuid.UUID
	Authority string
	Symbol    string
}

type Tier struct {
	ID         uuid.UUID
	Consortium uuid.UUID
	Name       *string
	Level      string
	Type       string
	Cost       float64
}
