// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAddressComponent = `-- name: CreateAddressComponent :one
INSERT INTO address_components (
  address, seq, type, value
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, address, seq, type, value
`

type CreateAddressComponentParams struct {
	Address uuid.UUID
	Seq     int32
	Type    string
	Value   string
}

func (q *Queries) CreateAddressComponent(ctx context.Context, arg CreateAddressComponentParams) (AddressComponent, error) {
	row := q.db.QueryRow(ctx, createAddressComponent,
		arg.Address,
		arg.Seq,
		arg.Type,
		arg.Value,
	)
	var i AddressComponent
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Seq,
		&i.Type,
		&i.Value,
	)
	return i, err
}

const createClosure = `-- name: CreateClosure :one
INSERT INTO closures (
  entry, start_date, end_date, reason
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, entry, start_date, end_date, reason
`

type CreateClosureParams struct {
	Entry     uuid.UUID
	StartDate pgtype.Timestamp
	EndDate   pgtype.Timestamp
	Reason    string
}

func (q *Queries) CreateClosure(ctx context.Context, arg CreateClosureParams) (Closure, error) {
	row := q.db.QueryRow(ctx, createClosure,
		arg.Entry,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
	)
	var i Closure
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  name, description, contact_name, from_email, tenant, vendor, phone_number, time_zone, organization_id, type, parent, lms_location_code, lender_of_last_resort
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, parent, name, type, description, organization_id, contact_name, from_email, tenant, vendor, phone_number, lms_location_code, lender_of_last_resort, hrid, time_zone
`

type CreateEntryParams struct {
	Name               string
	Description        *string
	ContactName        *string
	FromEmail          *string
	Tenant             *string
	Vendor             *string
	PhoneNumber        *string
	TimeZone           *string
	OrganizationID     *string
	Type               string
	Parent             *uuid.UUID
	LmsLocationCode    *string
	LenderOfLastResort []string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.Name,
		arg.Description,
		arg.ContactName,
		arg.FromEmail,
		arg.Tenant,
		arg.Vendor,
		arg.PhoneNumber,
		arg.TimeZone,
		arg.OrganizationID,
		arg.Type,
		arg.Parent,
		arg.LmsLocationCode,
		arg.LenderOfLastResort,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.OrganizationID,
		&i.ContactName,
		&i.FromEmail,
		&i.Tenant,
		&i.Vendor,
		&i.PhoneNumber,
		&i.LmsLocationCode,
		&i.LenderOfLastResort,
		&i.Hrid,
		&i.TimeZone,
	)
	return i, err
}

const createEntryNetwork = `-- name: CreateEntryNetwork :one
INSERT INTO entry_networks (
  entry, network
) VALUES (
  $1,
  $2
)
RETURNING id, entry, network
`

type CreateEntryNetworkParams struct {
	Entry   uuid.UUID
	Network uuid.UUID
}

func (q *Queries) CreateEntryNetwork(ctx context.Context, arg CreateEntryNetworkParams) (EntryNetwork, error) {
	row := q.db.QueryRow(ctx, createEntryNetwork, arg.Entry, arg.Network)
	var i EntryNetwork
	err := row.Scan(&i.ID, &i.Entry, &i.Network)
	return i, err
}

const createEntryTier = `-- name: CreateEntryTier :one
INSERT INTO entry_tiers (
  entry, tier
) VALUES (
  $1,
  $2
)
RETURNING id, entry, tier
`

type CreateEntryTierParams struct {
	Entry uuid.UUID
	Tier  uuid.UUID
}

func (q *Queries) CreateEntryTier(ctx context.Context, arg CreateEntryTierParams) (EntryTier, error) {
	row := q.db.QueryRow(ctx, createEntryTier, arg.Entry, arg.Tier)
	var i EntryTier
	err := row.Scan(&i.ID, &i.Entry, &i.Tier)
	return i, err
}

const createNetwork = `-- name: CreateNetwork :one
INSERT INTO networks (
  name, consortium, priority, reciprocal
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, consortium, name, priority, reciprocal
`

type CreateNetworkParams struct {
	Name       *string
	Consortium uuid.UUID
	Priority   float64
	Reciprocal *bool
}

func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, createNetwork,
		arg.Name,
		arg.Consortium,
		arg.Priority,
		arg.Reciprocal,
	)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Consortium,
		&i.Name,
		&i.Priority,
		&i.Reciprocal,
	)
	return i, err
}

const createTier = `-- name: CreateTier :one
INSERT INTO tiers (
  name, consortium, level, type, cost
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, consortium, name, level, type, cost
`

type CreateTierParams struct {
	Name       *string
	Consortium uuid.UUID
	Level      string
	Type       string
	Cost       float64
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (Tier, error) {
	row := q.db.QueryRow(ctx, createTier,
		arg.Name,
		arg.Consortium,
		arg.Level,
		arg.Type,
		arg.Cost,
	)
	var i Tier
	err := row.Scan(
		&i.ID,
		&i.Consortium,
		&i.Name,
		&i.Level,
		&i.Type,
		&i.Cost,
	)
	return i, err
}

const deleteAllOwnedAddressComponents = `-- name: DeleteAllOwnedAddressComponents :exec
DELETE FROM address_components WHERE address = $1
`

func (q *Queries) DeleteAllOwnedAddressComponents(ctx context.Context, address uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllOwnedAddressComponents, address)
	return err
}

const deleteAllOwnedAddresses = `-- name: DeleteAllOwnedAddresses :exec
DELETE FROM addresses WHERE entry = $1
`

func (q *Queries) DeleteAllOwnedAddresses(ctx context.Context, entry uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllOwnedAddresses, entry)
	return err
}

const deleteAllOwnedServiceEndpoints = `-- name: DeleteAllOwnedServiceEndpoints :exec
DELETE FROM service_endpoints WHERE entry = $1
`

func (q *Queries) DeleteAllOwnedServiceEndpoints(ctx context.Context, entry uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllOwnedServiceEndpoints, entry)
	return err
}

const deleteAllOwnedSymbols = `-- name: DeleteAllOwnedSymbols :exec
DELETE FROM symbols WHERE owner = $1
`

func (q *Queries) DeleteAllOwnedSymbols(ctx context.Context, owner uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllOwnedSymbols, owner)
	return err
}

const deleteClosureById = `-- name: DeleteClosureById :exec
DELETE from closures where id = $1
`

func (q *Queries) DeleteClosureById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClosureById, id)
	return err
}

const deleteEntryById = `-- name: DeleteEntryById :exec
DELETE from entries WHERE id = $1
`

func (q *Queries) DeleteEntryById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntryById, id)
	return err
}

const deleteEntryBySymbol = `-- name: DeleteEntryBySymbol :exec
DELETE from entries USING symbols
WHERE entries.id = symbols.owner
  AND symbols.authority = $1
  AND symbols.symbol = $2
`

type DeleteEntryBySymbolParams struct {
	Authority string
	Symbol    string
}

func (q *Queries) DeleteEntryBySymbol(ctx context.Context, arg DeleteEntryBySymbolParams) error {
	_, err := q.db.Exec(ctx, deleteEntryBySymbol, arg.Authority, arg.Symbol)
	return err
}

const deleteEntryNetworkById = `-- name: DeleteEntryNetworkById :exec
DELETE from entry_networks WHERE id = $1
`

func (q *Queries) DeleteEntryNetworkById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntryNetworkById, id)
	return err
}

const deleteEntryTierById = `-- name: DeleteEntryTierById :exec
DELETE from entry_tiers WHERE id = $1
`

func (q *Queries) DeleteEntryTierById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntryTierById, id)
	return err
}

const deleteHoldingsConfigByEntry = `-- name: DeleteHoldingsConfigByEntry :exec
DELETE FROM holdings_configs WHERE entry = $1
`

func (q *Queries) DeleteHoldingsConfigByEntry(ctx context.Context, entry uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHoldingsConfigByEntry, entry)
	return err
}

const deleteNetworkById = `-- name: DeleteNetworkById :exec
DELETE from networks where id = $1
`

func (q *Queries) DeleteNetworkById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNetworkById, id)
	return err
}

const deleteOtherOwnedAddresses = `-- name: DeleteOtherOwnedAddresses :exec
DELETE FROM addresses WHERE entry = $1 AND ID <> ALL($2::uuid[])
`

type DeleteOtherOwnedAddressesParams struct {
	Entry uuid.UUID
	Ids   []uuid.UUID
}

func (q *Queries) DeleteOtherOwnedAddresses(ctx context.Context, arg DeleteOtherOwnedAddressesParams) error {
	_, err := q.db.Exec(ctx, deleteOtherOwnedAddresses, arg.Entry, arg.Ids)
	return err
}

const deleteOtherOwnedServiceEndpoints = `-- name: DeleteOtherOwnedServiceEndpoints :exec
DELETE FROM service_endpoints WHERE entry = $1 AND ID <> ALL($2::uuid[])
`

type DeleteOtherOwnedServiceEndpointsParams struct {
	Entry uuid.UUID
	Ids   []uuid.UUID
}

func (q *Queries) DeleteOtherOwnedServiceEndpoints(ctx context.Context, arg DeleteOtherOwnedServiceEndpointsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherOwnedServiceEndpoints, arg.Entry, arg.Ids)
	return err
}

const deleteOtherOwnedSymbols = `-- name: DeleteOtherOwnedSymbols :exec
DELETE FROM symbols WHERE owner = $1 AND ID <> ALL($2::uuid[])
`

type DeleteOtherOwnedSymbolsParams struct {
	Owner uuid.UUID
	Ids   []uuid.UUID
}

func (q *Queries) DeleteOtherOwnedSymbols(ctx context.Context, arg DeleteOtherOwnedSymbolsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherOwnedSymbols, arg.Owner, arg.Ids)
	return err
}

const deleteTierById = `-- name: DeleteTierById :exec
DELETE from tiers where id = $1
`

func (q *Queries) DeleteTierById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTierById, id)
	return err
}

const entriesByParent = `-- name: EntriesByParent :many
SELECT id, parent, name, type, description, organization_id, contact_name, from_email, tenant, vendor, phone_number, lms_location_code, lender_of_last_resort, hrid, time_zone FROM entries WHERE parent = $1
`

func (q *Queries) EntriesByParent(ctx context.Context, parent *uuid.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, entriesByParent, parent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Parent,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.OrganizationID,
			&i.ContactName,
			&i.FromEmail,
			&i.Tenant,
			&i.Vendor,
			&i.PhoneNumber,
			&i.LmsLocationCode,
			&i.LenderOfLastResort,
			&i.Hrid,
			&i.TimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryById = `-- name: EntryById :one
SELECT id, parent, name, type, description, organization_id, contact_name, from_email, tenant, vendor, phone_number, lms_location_code, lender_of_last_resort, hrid, time_zone FROM entries WHERE id = $1 LIMIT 1
`

func (q *Queries) EntryById(ctx context.Context, id uuid.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, entryById, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.OrganizationID,
		&i.ContactName,
		&i.FromEmail,
		&i.Tenant,
		&i.Vendor,
		&i.PhoneNumber,
		&i.LmsLocationCode,
		&i.LenderOfLastResort,
		&i.Hrid,
		&i.TimeZone,
	)
	return i, err
}

const entryByIdForUpdate = `-- name: EntryByIdForUpdate :one
SELECT id, parent, name, type, description, organization_id, contact_name, from_email, tenant, vendor, phone_number, lms_location_code, lender_of_last_resort, hrid, time_zone FROM entries WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) EntryByIdForUpdate(ctx context.Context, id uuid.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, entryByIdForUpdate, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.OrganizationID,
		&i.ContactName,
		&i.FromEmail,
		&i.Tenant,
		&i.Vendor,
		&i.PhoneNumber,
		&i.LmsLocationCode,
		&i.LenderOfLastResort,
		&i.Hrid,
		&i.TimeZone,
	)
	return i, err
}

const entryBySymbol = `-- name: EntryBySymbol :one
SELECT e.id, e.parent, e.name, e.type, e.description, e.organization_id, e.contact_name, e.from_email, e.tenant, e.vendor, e.phone_number, e.lms_location_code, e.lender_of_last_resort, e.hrid, e.time_zone FROM entries e, symbols s WHERE e.id = s.owner AND s.authority = $1 AND s.symbol = $2 LIMIT 1
`

type EntryBySymbolParams struct {
	Authority string
	Symbol    string
}

func (q *Queries) EntryBySymbol(ctx context.Context, arg EntryBySymbolParams) (Entry, error) {
	row := q.db.QueryRow(ctx, entryBySymbol, arg.Authority, arg.Symbol)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.OrganizationID,
		&i.ContactName,
		&i.FromEmail,
		&i.Tenant,
		&i.Vendor,
		&i.PhoneNumber,
		&i.LmsLocationCode,
		&i.LenderOfLastResort,
		&i.Hrid,
		&i.TimeZone,
	)
	return i, err
}

const entryBySymbolForUpdate = `-- name: EntryBySymbolForUpdate :one
SELECT e.id, e.parent, e.name, e.type, e.description, e.organization_id, e.contact_name, e.from_email, e.tenant, e.vendor, e.phone_number, e.lms_location_code, e.lender_of_last_resort, e.hrid, e.time_zone FROM entries e, symbols s WHERE e.id = s.owner AND s.authority = $1 AND s.symbol = $2 LIMIT 1 FOR UPDATE OF e
`

type EntryBySymbolForUpdateParams struct {
	Authority string
	Symbol    string
}

func (q *Queries) EntryBySymbolForUpdate(ctx context.Context, arg EntryBySymbolForUpdateParams) (Entry, error) {
	row := q.db.QueryRow(ctx, entryBySymbolForUpdate, arg.Authority, arg.Symbol)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.OrganizationID,
		&i.ContactName,
		&i.FromEmail,
		&i.Tenant,
		&i.Vendor,
		&i.PhoneNumber,
		&i.LmsLocationCode,
		&i.LenderOfLastResort,
		&i.Hrid,
		&i.TimeZone,
	)
	return i, err
}

const getClosureById = `-- name: GetClosureById :one
SELECT id, entry, start_date, end_date, reason FROM closures WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClosureById(ctx context.Context, id uuid.UUID) (Closure, error) {
	row := q.db.QueryRow(ctx, getClosureById, id)
	var i Closure
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
	)
	return i, err
}

const getClosureByIdForUpdate = `-- name: GetClosureByIdForUpdate :one
SELECT id, entry, start_date, end_date, reason FROM closures WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetClosureByIdForUpdate(ctx context.Context, id uuid.UUID) (Closure, error) {
	row := q.db.QueryRow(ctx, getClosureByIdForUpdate, id)
	var i Closure
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
	)
	return i, err
}

const getConsortialEntry = `-- name: GetConsortialEntry :one
SELECT id, parent, name, type, description, organization_id, contact_name, from_email, tenant, vendor, phone_number, lms_location_code, lender_of_last_resort, hrid, time_zone FROM entries WHERE type = 'Consortium' LIMIT 1
`

func (q *Queries) GetConsortialEntry(ctx context.Context) (Entry, error) {
	row := q.db.QueryRow(ctx, getConsortialEntry)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.OrganizationID,
		&i.ContactName,
		&i.FromEmail,
		&i.Tenant,
		&i.Vendor,
		&i.PhoneNumber,
		&i.LmsLocationCode,
		&i.LenderOfLastResort,
		&i.Hrid,
		&i.TimeZone,
	)
	return i, err
}

const getEntryNetworkById = `-- name: GetEntryNetworkById :one
SELECT id, entry, network FROM entry_networks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntryNetworkById(ctx context.Context, id uuid.UUID) (EntryNetwork, error) {
	row := q.db.QueryRow(ctx, getEntryNetworkById, id)
	var i EntryNetwork
	err := row.Scan(&i.ID, &i.Entry, &i.Network)
	return i, err
}

const getEntryNetworkByNetworkAndEntry = `-- name: GetEntryNetworkByNetworkAndEntry :one
SELECT id, entry, network FROM entry_networks WHERE network = $1 AND entry = $2 LIMIT 1
`

type GetEntryNetworkByNetworkAndEntryParams struct {
	Network uuid.UUID
	Entry   uuid.UUID
}

func (q *Queries) GetEntryNetworkByNetworkAndEntry(ctx context.Context, arg GetEntryNetworkByNetworkAndEntryParams) (EntryNetwork, error) {
	row := q.db.QueryRow(ctx, getEntryNetworkByNetworkAndEntry, arg.Network, arg.Entry)
	var i EntryNetwork
	err := row.Scan(&i.ID, &i.Entry, &i.Network)
	return i, err
}

const getEntryTierById = `-- name: GetEntryTierById :one
SELECT id, entry, tier FROM entry_tiers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntryTierById(ctx context.Context, id uuid.UUID) (EntryTier, error) {
	row := q.db.QueryRow(ctx, getEntryTierById, id)
	var i EntryTier
	err := row.Scan(&i.ID, &i.Entry, &i.Tier)
	return i, err
}

const getEntryTierByTierAndEntry = `-- name: GetEntryTierByTierAndEntry :one
SELECT id, entry, tier FROM entry_tiers WHERE tier = $1 AND entry = $2 LIMIT 1
`

type GetEntryTierByTierAndEntryParams struct {
	Tier  uuid.UUID
	Entry uuid.UUID
}

func (q *Queries) GetEntryTierByTierAndEntry(ctx context.Context, arg GetEntryTierByTierAndEntryParams) (EntryTier, error) {
	row := q.db.QueryRow(ctx, getEntryTierByTierAndEntry, arg.Tier, arg.Entry)
	var i EntryTier
	err := row.Scan(&i.ID, &i.Entry, &i.Tier)
	return i, err
}

const getHoldingsConfigByEntry = `-- name: GetHoldingsConfigByEntry :one
SELECT id, entry, metadata_update_mode, sru_address, sru_record_schema, zoom_address, zoom_option_mock_records, zoom_option_preferred_record_syntax, zoom_option_count, zoom_option_element_set_name, zoom_option_schema, zoom_option_authentication, zoom_option_user, zoom_option_password, zoom_option_adapter_error, zoom_option_lookup_error, zoom_option_location, query_type, query_identifier, query_isbn, query_issn, query_title, holdings_marc_call_number_subfield, holdings_marc_item_id_subfield, holdings_marc_location_subfield, holdings_marc_main_field, holdings_marc_restricted_subfield, holdings_marc_shelving_location_subfield, holdings_marc21plus1_enabled, holdings_opac_enabled, holdings_reservoir_enabled, metadata_marc21_author, metadata_marc21_edition, metadata_marc21_identifier, metadata_marc21_isbn, metadata_marc21_issn, metadata_marc21_subtitle, metadata_marc21_title FROM holdings_configs
  WHERE entry = $1
`

func (q *Queries) GetHoldingsConfigByEntry(ctx context.Context, entry uuid.UUID) (HoldingsConfig, error) {
	row := q.db.QueryRow(ctx, getHoldingsConfigByEntry, entry)
	var i HoldingsConfig
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.MetadataUpdateMode,
		&i.SruAddress,
		&i.SruRecordSchema,
		&i.ZoomAddress,
		&i.ZoomOptionMockRecords,
		&i.ZoomOptionPreferredRecordSyntax,
		&i.ZoomOptionCount,
		&i.ZoomOptionElementSetName,
		&i.ZoomOptionSchema,
		&i.ZoomOptionAuthentication,
		&i.ZoomOptionUser,
		&i.ZoomOptionPassword,
		&i.ZoomOptionAdapterError,
		&i.ZoomOptionLookupError,
		&i.ZoomOptionLocation,
		&i.QueryType,
		&i.QueryIdentifier,
		&i.QueryIsbn,
		&i.QueryIssn,
		&i.QueryTitle,
		&i.HoldingsMarcCallNumberSubfield,
		&i.HoldingsMarcItemIDSubfield,
		&i.HoldingsMarcLocationSubfield,
		&i.HoldingsMarcMainField,
		&i.HoldingsMarcRestrictedSubfield,
		&i.HoldingsMarcShelvingLocationSubfield,
		&i.HoldingsMarc21plus1Enabled,
		&i.HoldingsOpacEnabled,
		&i.HoldingsReservoirEnabled,
		&i.MetadataMarc21Author,
		&i.MetadataMarc21Edition,
		&i.MetadataMarc21Identifier,
		&i.MetadataMarc21Isbn,
		&i.MetadataMarc21Issn,
		&i.MetadataMarc21Subtitle,
		&i.MetadataMarc21Title,
	)
	return i, err
}

const getLMSConfigByEntry = `-- name: GetLMSConfigByEntry :one
SELECT id, entry, address, from_agency, from_agency_authentication, to_agency, lookup_user_enabled, accept_item_enabled, checkin_item_enabled, checkout_item_enabled, item_location, request_item_request_type, request_item_scope_type, request_item_bib_code, request_item_pickup_location_enabled, requester_pickup_location, supplier_pickup_location, requester_patron_pattern FROM lms_configs 
  WHERE entry = $1
`

func (q *Queries) GetLMSConfigByEntry(ctx context.Context, entry uuid.UUID) (LmsConfig, error) {
	row := q.db.QueryRow(ctx, getLMSConfigByEntry, entry)
	var i LmsConfig
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.Address,
		&i.FromAgency,
		&i.FromAgencyAuthentication,
		&i.ToAgency,
		&i.LookupUserEnabled,
		&i.AcceptItemEnabled,
		&i.CheckinItemEnabled,
		&i.CheckoutItemEnabled,
		&i.ItemLocation,
		&i.RequestItemRequestType,
		&i.RequestItemScopeType,
		&i.RequestItemBibCode,
		&i.RequestItemPickupLocationEnabled,
		&i.RequesterPickupLocation,
		&i.SupplierPickupLocation,
		&i.RequesterPatronPattern,
	)
	return i, err
}

const getNetworkById = `-- name: GetNetworkById :one
SELECT id, consortium, name, priority, reciprocal FROM networks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNetworkById(ctx context.Context, id uuid.UUID) (Network, error) {
	row := q.db.QueryRow(ctx, getNetworkById, id)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Consortium,
		&i.Name,
		&i.Priority,
		&i.Reciprocal,
	)
	return i, err
}

const getTierById = `-- name: GetTierById :one
SELECT id, consortium, name, level, type, cost FROM tiers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTierById(ctx context.Context, id uuid.UUID) (Tier, error) {
	row := q.db.QueryRow(ctx, getTierById, id)
	var i Tier
	err := row.Scan(
		&i.ID,
		&i.Consortium,
		&i.Name,
		&i.Level,
		&i.Type,
		&i.Cost,
	)
	return i, err
}

const listClosures = `-- name: ListClosures :many
SELECT id, entry, start_date, end_date, reason FROM closures
  LIMIT $2
  OFFSET $1
`

type ListClosuresParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListClosures(ctx context.Context, arg ListClosuresParams) ([]Closure, error) {
	rows, err := q.db.Query(ctx, listClosures, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Closure
	for rows.Next() {
		var i Closure
		if err := rows.Scan(
			&i.ID,
			&i.Entry,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryNetworks = `-- name: ListEntryNetworks :many
SELECT id, entry, network FROM entry_networks
  WHERE (
    $1::text IS NULL
    OR $2::text IS NULL
    OR CASE $1::text
      WHEN 'id' THEN id::text
      WHEN 'entry' THEN entry::text
      WHEN 'network' THEN network::text
    END = $2::text
  )
  LIMIT $4
  OFFSET $3
`

type ListEntryNetworksParams struct {
	Field  *string
	Value  *string
	Offset int32
	Limit  int32
}

func (q *Queries) ListEntryNetworks(ctx context.Context, arg ListEntryNetworksParams) ([]EntryNetwork, error) {
	rows, err := q.db.Query(ctx, listEntryNetworks,
		arg.Field,
		arg.Value,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryNetwork
	for rows.Next() {
		var i EntryNetwork
		if err := rows.Scan(&i.ID, &i.Entry, &i.Network); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryTiers = `-- name: ListEntryTiers :many
SELECT id, entry, tier FROM entry_tiers
  WHERE (
    $1::text IS NULL
    OR $2::text IS NULL
    OR CASE $1::text
      WHEN 'id' THEN id::text
      WHEN 'entry' THEN entry::text
      WHEN 'tier' THEN tier::text
    END = $2::text
  )
  LIMIT $4
  OFFSET $3
`

type ListEntryTiersParams struct {
	Field  *string
	Value  *string
	Offset int32
	Limit  int32
}

func (q *Queries) ListEntryTiers(ctx context.Context, arg ListEntryTiersParams) ([]EntryTier, error) {
	rows, err := q.db.Query(ctx, listEntryTiers,
		arg.Field,
		arg.Value,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryTier
	for rows.Next() {
		var i EntryTier
		if err := rows.Scan(&i.ID, &i.Entry, &i.Tier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworks = `-- name: ListNetworks :many
SELECT id, consortium, name, priority, reciprocal FROM networks
  LIMIT $2
  OFFSET $1
`

type ListNetworksParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListNetworks(ctx context.Context, arg ListNetworksParams) ([]Network, error) {
	rows, err := q.db.Query(ctx, listNetworks, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Network
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.Consortium,
			&i.Name,
			&i.Priority,
			&i.Reciprocal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworksForConsortium = `-- name: ListNetworksForConsortium :many
SELECT id, consortium, name, priority, reciprocal FROM networks
WHERE consortium = $1
`

func (q *Queries) ListNetworksForConsortium(ctx context.Context, consortium uuid.UUID) ([]Network, error) {
	rows, err := q.db.Query(ctx, listNetworksForConsortium, consortium)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Network
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.Consortium,
			&i.Name,
			&i.Priority,
			&i.Reciprocal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworksForEntry = `-- name: ListNetworksForEntry :many
SELECT n.id, consortium, name, priority, reciprocal, en.id, entry, network FROM networks n
JOIN entry_networks en ON n.id = en.network
WHERE en.entry = $1
`

type ListNetworksForEntryRow struct {
	ID         uuid.UUID
	Consortium uuid.UUID
	Name       *string
	Priority   float64
	Reciprocal *bool
	ID_2       uuid.UUID
	Entry      uuid.UUID
	Network    uuid.UUID
}

func (q *Queries) ListNetworksForEntry(ctx context.Context, entry uuid.UUID) ([]ListNetworksForEntryRow, error) {
	rows, err := q.db.Query(ctx, listNetworksForEntry, entry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNetworksForEntryRow
	for rows.Next() {
		var i ListNetworksForEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.Consortium,
			&i.Name,
			&i.Priority,
			&i.Reciprocal,
			&i.ID_2,
			&i.Entry,
			&i.Network,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiers = `-- name: ListTiers :many
SELECT id, consortium, name, level, type, cost FROM tiers
  LIMIT $2
  OFFSET $1
`

type ListTiersParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListTiers(ctx context.Context, arg ListTiersParams) ([]Tier, error) {
	rows, err := q.db.Query(ctx, listTiers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tier
	for rows.Next() {
		var i Tier
		if err := rows.Scan(
			&i.ID,
			&i.Consortium,
			&i.Name,
			&i.Level,
			&i.Type,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiersForConsortium = `-- name: ListTiersForConsortium :many
SELECT id, consortium, name, level, type, cost FROM tiers
WHERE consortium = $1
`

func (q *Queries) ListTiersForConsortium(ctx context.Context, consortium uuid.UUID) ([]Tier, error) {
	rows, err := q.db.Query(ctx, listTiersForConsortium, consortium)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tier
	for rows.Next() {
		var i Tier
		if err := rows.Scan(
			&i.ID,
			&i.Consortium,
			&i.Name,
			&i.Level,
			&i.Type,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiersForEntry = `-- name: ListTiersForEntry :many
SELECT t.id, consortium, name, level, type, cost, et.id, entry, tier FROM tiers t
JOIN entry_tiers et ON t.id = et.tier
WHERE et.entry = $1
`

type ListTiersForEntryRow struct {
	ID         uuid.UUID
	Consortium uuid.UUID
	Name       *string
	Level      string
	Type       string
	Cost       float64
	ID_2       uuid.UUID
	Entry      uuid.UUID
	Tier       uuid.UUID
}

func (q *Queries) ListTiersForEntry(ctx context.Context, entry uuid.UUID) ([]ListTiersForEntryRow, error) {
	rows, err := q.db.Query(ctx, listTiersForEntry, entry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTiersForEntryRow
	for rows.Next() {
		var i ListTiersForEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.Consortium,
			&i.Name,
			&i.Level,
			&i.Type,
			&i.Cost,
			&i.ID_2,
			&i.Entry,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConsortiumEntryChanges = `-- name: LockConsortiumEntryChanges :exec
SELECT pg_advisory_xact_lock(hashtextextended('directoryish:consortium-entry', 0))
`

func (q *Queries) LockConsortiumEntryChanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockConsortiumEntryChanges)
	return err
}

const updateClosure = `-- name: UpdateClosure :exec
UPDATE closures
SET
  start_date = $1,
  end_date = $2,
  reason = $3
WHERE id = $4
`

type UpdateClosureParams struct {
	StartDate pgtype.Timestamp
	EndDate   pgtype.Timestamp
	Reason    string
	ID        uuid.UUID
}

func (q *Queries) UpdateClosure(ctx context.Context, arg UpdateClosureParams) error {
	_, err := q.db.Exec(ctx, updateClosure,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
		arg.ID,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET
  name = $1,
  description = $2,
  contact_name = $3,
  from_email = $4,
  tenant = $5,
  vendor = $6,
  phone_number = $7,
  time_zone = $8,
  organization_id = $9,
  type = $10,
  parent = $11,
  lms_location_code = $12,
  lender_of_last_resort = $13,
  hrid = $14

WHERE id = $15
`

type UpdateEntryParams struct {
	Name               string
	Description        *string
	ContactName        *string
	FromEmail          *string
	Tenant             *string
	Vendor             *string
	PhoneNumber        *string
	TimeZone           *string
	OrganizationID     *string
	Type               string
	Parent             *uuid.UUID
	LmsLocationCode    *string
	LenderOfLastResort []string
	Hrid               *string
	ID                 uuid.UUID
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.Exec(ctx, updateEntry,
		arg.Name,
		arg.Description,
		arg.ContactName,
		arg.FromEmail,
		arg.Tenant,
		arg.Vendor,
		arg.PhoneNumber,
		arg.TimeZone,
		arg.OrganizationID,
		arg.Type,
		arg.Parent,
		arg.LmsLocationCode,
		arg.LenderOfLastResort,
		arg.Hrid,
		arg.ID,
	)
	return err
}

const upsertAddress = `-- name: UpsertAddress :one
INSERT INTO addresses (
  id, entry, type
) VALUES (
  coalesce($1, gen_random_uuid()),
  $2,
  $3
)
ON CONFLICT (id) DO UPDATE SET
  entry = $2,
  type = $3
WHERE addresses.id = $1
RETURNING id, entry, type
`

type UpsertAddressParams struct {
	ID    interface{}
	Entry uuid.UUID
	Type  string
}

func (q *Queries) UpsertAddress(ctx context.Context, arg UpsertAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, upsertAddress, arg.ID, arg.Entry, arg.Type)
	var i Address
	err := row.Scan(&i.ID, &i.Entry, &i.Type)
	return i, err
}

const upsertHoldingsConfig = `-- name: UpsertHoldingsConfig :one
INSERT INTO holdings_configs (
  id, entry, metadata_update_mode,
  sru_address, sru_record_schema,
  zoom_address, zoom_option_mock_records, zoom_option_preferred_record_syntax, zoom_option_count,
  zoom_option_element_set_name, zoom_option_schema, zoom_option_authentication, zoom_option_user, zoom_option_password,
  zoom_option_adapter_error, zoom_option_lookup_error, zoom_option_location,
  query_type, query_identifier, query_isbn, query_issn, query_title,
  holdings_marc_call_number_subfield, holdings_marc_item_id_subfield, holdings_marc_location_subfield,
  holdings_marc_main_field, holdings_marc_restricted_subfield, holdings_marc_shelving_location_subfield,
  holdings_marc21plus1_enabled, holdings_opac_enabled, holdings_reservoir_enabled,
  metadata_marc21_author, metadata_marc21_edition, metadata_marc21_identifier, metadata_marc21_isbn,
  metadata_marc21_issn, metadata_marc21_subtitle, metadata_marc21_title
) VALUES (
  coalesce($1, gen_random_uuid()),
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29,
  $30,
  $31,
  $32,
  $33,
  $34,
  $35,
  $36,
  $37,
  $38
)
ON CONFLICT (entry) DO UPDATE SET
  metadata_update_mode = $3,
  sru_address = $4,
  sru_record_schema = $5,
  zoom_address = $6,
  zoom_option_mock_records = $7,
  zoom_option_preferred_record_syntax = $8,
  zoom_option_count = $9,
  zoom_option_element_set_name = $10,
  zoom_option_schema = $11,
  zoom_option_authentication = $12,
  zoom_option_user = $13,
  zoom_option_password = $14,
  zoom_option_adapter_error = $15,
  zoom_option_lookup_error = $16,
  zoom_option_location = $17,
  query_type = $18,
  query_identifier = $19,
  query_isbn = $20,
  query_issn = $21,
  query_title = $22,
  holdings_marc_call_number_subfield = $23,
  holdings_marc_item_id_subfield = $24,
  holdings_marc_location_subfield = $25,
  holdings_marc_main_field = $26,
  holdings_marc_restricted_subfield = $27,
  holdings_marc_shelving_location_subfield = $28,
  holdings_marc21plus1_enabled = $29,
  holdings_opac_enabled = $30,
  holdings_reservoir_enabled = $31,
  metadata_marc21_author = $32,
  metadata_marc21_edition = $33,
  metadata_marc21_identifier = $34,
  metadata_marc21_isbn = $35,
  metadata_marc21_issn = $36,
  metadata_marc21_subtitle = $37,
  metadata_marc21_title = $38
WHERE holdings_configs.entry = $2
RETURNING id, entry, metadata_update_mode, sru_address, sru_record_schema, zoom_address, zoom_option_mock_records, zoom_option_preferred_record_syntax, zoom_option_count, zoom_option_element_set_name, zoom_option_schema, zoom_option_authentication, zoom_option_user, zoom_option_password, zoom_option_adapter_error, zoom_option_lookup_error, zoom_option_location, query_type, query_identifier, query_isbn, query_issn, query_title, holdings_marc_call_number_subfield, holdings_marc_item_id_subfield, holdings_marc_location_subfield, holdings_marc_main_field, holdings_marc_restricted_subfield, holdings_marc_shelving_location_subfield, holdings_marc21plus1_enabled, holdings_opac_enabled, holdings_reservoir_enabled, metadata_marc21_author, metadata_marc21_edition, metadata_marc21_identifier, metadata_marc21_isbn, metadata_marc21_issn, metadata_marc21_subtitle, metadata_marc21_title
`

type UpsertHoldingsConfigParams struct {
	ID                                   interface{}
	Entry                                *uuid.UUID
	MetadataUpdateMode                   *string
	SruAddress                           *string
	SruRecordSchema                      *string
	ZoomAddress                          *string
	ZoomOptionMockRecords                *string
	ZoomOptionPreferredRecordSyntax      *string
	ZoomOptionCount                      *string
	ZoomOptionElementSetName             *string
	ZoomOptionSchema                     *string
	ZoomOptionAuthentication             *string
	ZoomOptionUser                       *string
	ZoomOptionPassword                   *string
	ZoomOptionAdapterError               *string
	ZoomOptionLookupError                *string
	ZoomOptionLocation                   *string
	QueryType                            *string
	QueryIdentifier                      *string
	QueryIsbn                            *string
	QueryIssn                            *string
	QueryTitle                           *string
	HoldingsMarcCallNumberSubfield       *string
	HoldingsMarcItemIDSubfield           *string
	HoldingsMarcLocationSubfield         *string
	HoldingsMarcMainField                *string
	HoldingsMarcRestrictedSubfield       *string
	HoldingsMarcShelvingLocationSubfield *string
	HoldingsMarc21plus1Enabled           *bool
	HoldingsOpacEnabled                  *bool
	HoldingsReservoirEnabled             *bool
	MetadataMarc21Author                 *string
	MetadataMarc21Edition                *string
	MetadataMarc21Identifier             *string
	MetadataMarc21Isbn                   *string
	MetadataMarc21Issn                   *string
	MetadataMarc21Subtitle               *string
	MetadataMarc21Title                  *string
}

func (q *Queries) UpsertHoldingsConfig(ctx context.Context, arg UpsertHoldingsConfigParams) (HoldingsConfig, error) {
	row := q.db.QueryRow(ctx, upsertHoldingsConfig,
		arg.ID,
		arg.Entry,
		arg.MetadataUpdateMode,
		arg.SruAddress,
		arg.SruRecordSchema,
		arg.ZoomAddress,
		arg.ZoomOptionMockRecords,
		arg.ZoomOptionPreferredRecordSyntax,
		arg.ZoomOptionCount,
		arg.ZoomOptionElementSetName,
		arg.ZoomOptionSchema,
		arg.ZoomOptionAuthentication,
		arg.ZoomOptionUser,
		arg.ZoomOptionPassword,
		arg.ZoomOptionAdapterError,
		arg.ZoomOptionLookupError,
		arg.ZoomOptionLocation,
		arg.QueryType,
		arg.QueryIdentifier,
		arg.QueryIsbn,
		arg.QueryIssn,
		arg.QueryTitle,
		arg.HoldingsMarcCallNumberSubfield,
		arg.HoldingsMarcItemIDSubfield,
		arg.HoldingsMarcLocationSubfield,
		arg.HoldingsMarcMainField,
		arg.HoldingsMarcRestrictedSubfield,
		arg.HoldingsMarcShelvingLocationSubfield,
		arg.HoldingsMarc21plus1Enabled,
		arg.HoldingsOpacEnabled,
		arg.HoldingsReservoirEnabled,
		arg.MetadataMarc21Author,
		arg.MetadataMarc21Edition,
		arg.MetadataMarc21Identifier,
		arg.MetadataMarc21Isbn,
		arg.MetadataMarc21Issn,
		arg.MetadataMarc21Subtitle,
		arg.MetadataMarc21Title,
	)
	var i HoldingsConfig
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.MetadataUpdateMode,
		&i.SruAddress,
		&i.SruRecordSchema,
		&i.ZoomAddress,
		&i.ZoomOptionMockRecords,
		&i.ZoomOptionPreferredRecordSyntax,
		&i.ZoomOptionCount,
		&i.ZoomOptionElementSetName,
		&i.ZoomOptionSchema,
		&i.ZoomOptionAuthentication,
		&i.ZoomOptionUser,
		&i.ZoomOptionPassword,
		&i.ZoomOptionAdapterError,
		&i.ZoomOptionLookupError,
		&i.ZoomOptionLocation,
		&i.QueryType,
		&i.QueryIdentifier,
		&i.QueryIsbn,
		&i.QueryIssn,
		&i.QueryTitle,
		&i.HoldingsMarcCallNumberSubfield,
		&i.HoldingsMarcItemIDSubfield,
		&i.HoldingsMarcLocationSubfield,
		&i.HoldingsMarcMainField,
		&i.HoldingsMarcRestrictedSubfield,
		&i.HoldingsMarcShelvingLocationSubfield,
		&i.HoldingsMarc21plus1Enabled,
		&i.HoldingsOpacEnabled,
		&i.HoldingsReservoirEnabled,
		&i.MetadataMarc21Author,
		&i.MetadataMarc21Edition,
		&i.MetadataMarc21Identifier,
		&i.MetadataMarc21Isbn,
		&i.MetadataMarc21Issn,
		&i.MetadataMarc21Subtitle,
		&i.MetadataMarc21Title,
	)
	return i, err
}

const upsertLMSConfig = `-- name: UpsertLMSConfig :one
INSERT INTO  lms_configs (
  id, entry, address, from_agency, from_agency_authentication, to_agency, lookup_user_enabled,
  accept_item_enabled, checkin_item_enabled, checkout_item_enabled, item_location, 
  request_item_request_type, request_item_scope_type, request_item_bib_code,
  request_item_pickup_location_enabled, requester_pickup_location, supplier_pickup_location,
  requester_patron_pattern
) VALUES (
  coalesce($1, gen_random_uuid()),
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18
)
ON CONFLICT (entry) DO UPDATE SET
  address = $3,
  from_agency = $4,
  from_agency_authentication = $5,
  to_agency = $6,
  lookup_user_enabled = $7,
  accept_item_enabled = $8,
  checkin_item_enabled = $9,
  checkout_item_enabled = $10,
  item_location = $11,
  request_item_request_type = $12,
  request_item_scope_type = $13,
  request_item_bib_code = $14,
  request_item_pickup_location_enabled = $15,
  requester_pickup_location = $16,
  supplier_pickup_location = $17,
  requester_patron_pattern = $18
WHERE lms_configs.entry = $2
RETURNING id, entry, address, from_agency, from_agency_authentication, to_agency, lookup_user_enabled, accept_item_enabled, checkin_item_enabled, checkout_item_enabled, item_location, request_item_request_type, request_item_scope_type, request_item_bib_code, request_item_pickup_location_enabled, requester_pickup_location, supplier_pickup_location, requester_patron_pattern
`

type UpsertLMSConfigParams struct {
	ID                               interface{}
	Entry                            *uuid.UUID
	Address                          string
	FromAgency                       string
	FromAgencyAuthentication         *string
	ToAgency                         *string
	LookupUserEnabled                *bool
	AcceptItemEnabled                *bool
	CheckinItemEnabled               *bool
	CheckoutItemEnabled              *bool
	ItemLocation                     *string
	RequestItemRequestType           *string
	RequestItemScopeType             *string
	RequestItemBibCode               *string
	RequestItemPickupLocationEnabled *bool
	RequesterPickupLocation          *string
	SupplierPickupLocation           *string
	RequesterPatronPattern           *string
}

func (q *Queries) UpsertLMSConfig(ctx context.Context, arg UpsertLMSConfigParams) (LmsConfig, error) {
	row := q.db.QueryRow(ctx, upsertLMSConfig,
		arg.ID,
		arg.Entry,
		arg.Address,
		arg.FromAgency,
		arg.FromAgencyAuthentication,
		arg.ToAgency,
		arg.LookupUserEnabled,
		arg.AcceptItemEnabled,
		arg.CheckinItemEnabled,
		arg.CheckoutItemEnabled,
		arg.ItemLocation,
		arg.RequestItemRequestType,
		arg.RequestItemScopeType,
		arg.RequestItemBibCode,
		arg.RequestItemPickupLocationEnabled,
		arg.RequesterPickupLocation,
		arg.SupplierPickupLocation,
		arg.RequesterPatronPattern,
	)
	var i LmsConfig
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.Address,
		&i.FromAgency,
		&i.FromAgencyAuthentication,
		&i.ToAgency,
		&i.LookupUserEnabled,
		&i.AcceptItemEnabled,
		&i.CheckinItemEnabled,
		&i.CheckoutItemEnabled,
		&i.ItemLocation,
		&i.RequestItemRequestType,
		&i.RequestItemScopeType,
		&i.RequestItemBibCode,
		&i.RequestItemPickupLocationEnabled,
		&i.RequesterPickupLocation,
		&i.SupplierPickupLocation,
		&i.RequesterPatronPattern,
	)
	return i, err
}

const upsertServiceEndpoint = `-- name: UpsertServiceEndpoint :one
INSERT INTO service_endpoints (
  id, entry, name, type, address
) VALUES (
  coalesce($1, gen_random_uuid()),
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (id) DO UPDATE SET
  entry = $2,
  name = $3,
  type = $4,
  address = $5
WHERE service_endpoints.id = $1
RETURNING id, entry, name, type, address
`

type UpsertServiceEndpointParams struct {
	ID      interface{}
	Entry   uuid.UUID
	Name    string
	Type    string
	Address string
}

func (q *Queries) UpsertServiceEndpoint(ctx context.Context, arg UpsertServiceEndpointParams) (ServiceEndpoint, error) {
	row := q.db.QueryRow(ctx, upsertServiceEndpoint,
		arg.ID,
		arg.Entry,
		arg.Name,
		arg.Type,
		arg.Address,
	)
	var i ServiceEndpoint
	err := row.Scan(
		&i.ID,
		&i.Entry,
		&i.Name,
		&i.Type,
		&i.Address,
	)
	return i, err
}

const upsertSymbol = `-- name: UpsertSymbol :one
INSERT INTO symbols (
  id, owner, symbol, authority
) VALUES (
  coalesce($1, gen_random_uuid()),
  $2,
  $3,
  $4
)
ON CONFLICT (id) DO UPDATE SET
  owner = $2,
  symbol = $3,
  authority = $4
WHERE symbols.id = $1
RETURNING id, owner, authority, symbol
`

type UpsertSymbolParams struct {
	ID        interface{}
	Owner     uuid.UUID
	Symbol    string
	Authority string
}

func (q *Queries) UpsertSymbol(ctx context.Context, arg UpsertSymbolParams) (Symbol, error) {
	row := q.db.QueryRow(ctx, upsertSymbol,
		arg.ID,
		arg.Owner,
		arg.Symbol,
		arg.Authority,
	)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Authority,
		&i.Symbol,
	)
	return i, err
}
