openapi: 3.0.0
info:
  title: Patron Request API
  version: 1.0.0
  description: API for Patron Request CRUD and state actions

components:
  parameters:
    Tenant:
      name: X-Okapi-Tenant
      in: header
      description: Okapi Tenant
      required: false
      schema:
        type: string
        pattern: '^[_a-z][_a-z0-9]*$'

  schemas:
    StateModel:
      type: object
      description: ReShare state model definition
      additionalProperties: false
      properties:
        type:
          type: string
          const: StateModel
        name:
          type: string
          description: Name of the state model
        desc:
          type: string
          description: Description of the state model
        version:
          type: string
          description: Version of the state model in SemVer
        states:
          type: array
          description: A list of all allowed states
          items:
            $ref: '#/components/schemas/State'

    State:
      title: State
      type: object
      description: Definition of a particular state
      properties:
        name:
          type: string
          description: Name of the state, in capital letters with underscores
        display:
          type: string
          description: Human-readable state name
        desc:
          type: string
          description: Description of the state, e.g., what situation is modelled by the state
        side:
          type: string
          description: Indicates which side of the request the state belongs to
          enum: 
            - REQUESTER
            - SUPPLIER
        actions:
          type: array
          description: List of all actions that may be performed on the request when in this state
          items:
            $ref: '#/components/schemas/Action'
        events:
          type: array
          description: List of all events that may be triggered to the request when in this state
          items:
            $ref: '#/components/schemas/Event'
        terminal:
          type: boolean
          description: Indicates if the state is terminal (meaning no actions or events are allowed in this state)
      oneOf:
        - anyOf:
          - required:
            - actions
          - required:
            - events
        - required:
          - terminal
      required:
        - name
        - side

    Action:
      type: object
      title: Action
      additionalProperties: false
      properties:
        name:
          type: string
          description: Description of the action
        transitions:
          type: array
          description: List of all possible state transitions after performing the action. When no transitions are defined, the action is considered to be non-state-changing
          items:
            type: string
      required:
        - name

    Event:
      type: object
      title: Event
      additionalProperties: false
      properties:
        name:
          type: string
          description: Description of the event
        transitions:
          type: array
          description: List of all possible state transitions after performing the event. When no transitions are defined, the event is considered to be non-state-changing
          items:
            type: string
      required:
        - name

    PatronRequest:
      type: object
      properties:
        ID:
          type: string
          description: Unique identifier of the patron request
        Timestamp:
          type: string
          format: date-time
          description: Timestamp of the patron reuqest
        IllRequest:
          type: string
          description: JSON of ISO18626 request
        State:
          type: string
          description: Patron request state
        Side:
          type: string
          description: Patron request side - borrowing or lending
        Patron:
          type: string
          description: User who requested item
        RequesterSymbol:
          type: string
          description: Requester symbol
        SupplierSymbol:
          type: string
          description: Supplier symbol
      required:
        - ID
        - Timestamp
        - State
        - Side

    CreatePatronRequest:
      type: object
      properties:
        ID:
          type: string
          description: Unique identifier of the patron request
        Timestamp:
          type: string
          format: date-time
          description: Timestamp of the patron reuqest
        IllRequest:
          type: string
          description: JSON of ISO18626 request
        Patron:
          type: string
          description: User who requested item
        RequesterSymbol:
          type: string
          description: Requester symbol
        SupplierSymbol:
          type: string
          description: Supplier symbol
      required:
        - ID
        - Timestamp

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error

    ExecuteAction:
      type: object
      properties:
        action:
          type: string
          description: Action to execute
        actionParams:
          type: object
          description: Action parameters
      required:
        - action

    ActionResult:
      type: object
      properties:
        actionResult:
          type: string
          description: Action result
        message:
          type: string
          description: Action message
      required:
        - actionResult

paths:
  /state_model/models/{model}:
    get:
      summary: Retrieve a state model by name
      parameters:
        - in: path
          name: model
          schema: 
            type: string
          required: true
          description: The name of the statemodel to retrieve
        - $ref: '#/components/parameters/Tenant'
      responses:
        '200':
          description: Successful retrieval of state model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /patron_requests:
    get:
      summary: Retrieve patron requests
      responses:
        '200':
          description: Successful retrieval of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatronRequest'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new patron request
      parameters:
        - $ref: '#/components/parameters/Tenant'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePatronRequest'
      responses:
        '201':
          description: Patron request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatronRequest'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /patron_requests/{id}:
    get:
      summary: Get a patron request by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the patron request to retrieve
        - $ref: '#/components/parameters/Tenant'
      responses:
        '200':
          description: Successful retrieval of the patron request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatronRequest'
        '404':
          description: Patron request not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a patron request
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the patron request to delete
        - $ref: '#/components/parameters/Tenant'
      responses:
        '204':
          description: Patron request deleted successfully (No Content)
        '404':
          description: Patron request not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /patron_requests/{id}/actions:
    get:
      summary: Get valid actions for patron request in current state
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the patron request
        - $ref: '#/components/parameters/Tenant'
      responses:
        '200':
          description: List of available actions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
          description: Patron request not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: There was internal server error looking up patron request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /patron_requests/{id}/action:
    post:
      summary: Execute action for given patron request
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the patron request
        - $ref: '#/components/parameters/Tenant'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteAction'
      responses:
        '200':
          description: List of available actions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Patron request not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: There was internal server error looking up patron request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

