//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AddressType.
const (
	AddressTypeBilling  AddressType = "Billing"
	AddressTypeDefault  AddressType = "Default"
	AddressTypeOther    AddressType = "Other"
	AddressTypeShipping AddressType = "Shipping"
)

// Defines values for AddressComponentType.
const (
	AddressComponentTypeAdministrativeArea AddressComponentType = "AdministrativeArea"
	AddressComponentTypeCountryCode        AddressComponentType = "CountryCode"
	AddressComponentTypeLocality           AddressComponentType = "Locality"
	AddressComponentTypeOther              AddressComponentType = "Other"
	AddressComponentTypePostalCode         AddressComponentType = "PostalCode"
	AddressComponentTypeThoroughfare       AddressComponentType = "Thoroughfare"
)

// Defines values for AddressPatchType.
const (
	AddressPatchTypeBilling  AddressPatchType = "Billing"
	AddressPatchTypeDefault  AddressPatchType = "Default"
	AddressPatchTypeOther    AddressPatchType = "Other"
	AddressPatchTypeShipping AddressPatchType = "Shipping"
)

// Defines values for AddressPropertiesType.
const (
	AddressPropertiesTypeBilling  AddressPropertiesType = "Billing"
	AddressPropertiesTypeDefault  AddressPropertiesType = "Default"
	AddressPropertiesTypeOther    AddressPropertiesType = "Other"
	AddressPropertiesTypeShipping AddressPropertiesType = "Shipping"
)

// Defines values for EntryLookupKey.
const (
	EntryLookupKeyById     EntryLookupKey = "by-id"
	EntryLookupKeyBySymbol EntryLookupKey = "by-symbol"
)

// Defines values for DeleteEntryParamsKey.
const (
	DeleteEntryParamsKeyById     DeleteEntryParamsKey = "by-id"
	DeleteEntryParamsKeyBySymbol DeleteEntryParamsKey = "by-symbol"
)

// Defines values for GetEntryParamsKey.
const (
	GetEntryParamsKeyById     GetEntryParamsKey = "by-id"
	GetEntryParamsKeyBySymbol GetEntryParamsKey = "by-symbol"
)

// Defines values for UpdateEntryParamsKey.
const (
	UpdateEntryParamsKeyById     UpdateEntryParamsKey = "by-id"
	UpdateEntryParamsKeyBySymbol UpdateEntryParamsKey = "by-symbol"
)

// About defines model for About.
type About struct {
	// Count Total number of items in the result
	Count int64 `json:"count"`

	// NextLink Link to the next page of results
	NextLink *string `json:"nextLink,omitempty"`

	// PrevLink Link to the previous page of results
	PrevLink *string `json:"prevLink,omitempty"`
}

// Address defines model for Address.
type Address struct {
	AddressComponents *[]AddressComponent `json:"addressComponents,omitempty"`

	// Id Unique id
	Id   *openapi_types.UUID `json:"id,omitempty"`
	Type AddressType         `json:"type"`
}

// AddressType defines model for Address.Type.
type AddressType string

// AddressComponent defines model for AddressComponent.
type AddressComponent struct {
	// Seq Sequence number for ordering components
	Seq   int32                `json:"seq"`
	Type  AddressComponentType `json:"type"`
	Value string               `json:"value"`
}

// AddressComponentType defines model for AddressComponent.Type.
type AddressComponentType string

// AddressPatch defines model for AddressPatch.
type AddressPatch struct {
	AddressComponents *[]AddressComponent `json:"addressComponents,omitempty"`

	// Id Unique id
	Id   *openapi_types.UUID `json:"id,omitempty"`
	Type AddressPatchType    `json:"type"`
}

// AddressPatchType defines model for AddressPatch.Type.
type AddressPatchType string

// AddressProperties defines model for AddressProperties.
type AddressProperties struct {
	AddressComponents *[]AddressComponent   `json:"addressComponents,omitempty"`
	Type              AddressPropertiesType `json:"type"`
}

// AddressPropertiesType defines model for AddressProperties.Type.
type AddressPropertiesType string

// Consortium defines model for Consortium.
type Consortium struct {
	Entry *openapi_types.UUID `json:"entry,omitempty"`

	// Id Unique identifier
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Display name
	Name string `json:"name"`
}

// ConsortiumPatch defines model for ConsortiumPatch.
type ConsortiumPatch struct {
	Entry nullable.Nullable[openapi_types.UUID] `json:"entry,omitempty"`

	// Name Display name
	Name *string `json:"name,omitempty"`
}

// EntriesResponse defines model for EntriesResponse.
type EntriesResponse struct {
	About About   `json:"about"`
	Items []Entry `json:"items"`
}

// Entry defines model for Entry.
type Entry struct {
	// Addresses Addresses associated with this entry
	Addresses *[]Address `json:"addresses,omitempty"`

	// ContactName Name of contact person
	ContactName *string `json:"contactName,omitempty"`

	// Description Detailed description of the entity described by this entry
	Description *string `json:"description,omitempty"`

	// Email Main contact email
	Email *string `json:"email,omitempty"`

	// Endpoints Service endpoints associated with this entry
	Endpoints *[]ServiceEndpoint `json:"endpoints,omitempty"`

	// Id Unique id
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Name of the institution or branch this directory entry describes
	Name string `json:"name"`

	// Symbols Symbols associated with this entry
	Symbols *[]Symbol `json:"symbols,omitempty"`
}

// EntryPatch defines model for EntryPatch.
type EntryPatch struct {
	Addresses   nullable.Nullable[[]AddressPatch]         `json:"addresses,omitempty"`
	ContactName nullable.Nullable[string]                 `json:"contactName,omitempty"`
	Description nullable.Nullable[string]                 `json:"description,omitempty"`
	Email       nullable.Nullable[string]                 `json:"email,omitempty"`
	Endpoints   nullable.Nullable[[]ServiceEndpointPatch] `json:"endpoints,omitempty"`
	Name        *string                                   `json:"name,omitempty"`
	Symbols     nullable.Nullable[[]SymbolPatch]          `json:"symbols,omitempty"`
}

// Id defines model for Id.
type Id struct {
	// Id Unique id
	Id openapi_types.UUID `json:"id"`
}

// ServiceEndpoint defines model for ServiceEndpoint.
type ServiceEndpoint struct {
	Address string `json:"address"`

	// Id Unique id
	Id   *openapi_types.UUID `json:"id,omitempty"`
	Name string              `json:"name"`
	Type string              `json:"type"`
}

// ServiceEndpointPatch defines model for ServiceEndpointPatch.
type ServiceEndpointPatch struct {
	Address string `json:"address"`

	// Id Unique id
	Id   *openapi_types.UUID `json:"id,omitempty"`
	Name string              `json:"name"`
	Type string              `json:"type"`
}

// ServiceEndpointProperties defines model for ServiceEndpointProperties.
type ServiceEndpointProperties struct {
	Address string `json:"address"`
	Name    string `json:"name"`
	Type    string `json:"type"`
}

// Symbol defines model for Symbol.
type Symbol struct {
	// Authority Uppercase string
	Authority string `json:"authority"`

	// Id Unique id
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Symbol Uppercase string
	Symbol string `json:"symbol"`
}

// SymbolPatch defines model for SymbolPatch.
type SymbolPatch struct {
	// Authority Uppercase string
	Authority string `json:"authority"`

	// Id Unique id
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Symbol Uppercase string
	Symbol string `json:"symbol"`
}

// SymbolProperties defines model for SymbolProperties.
type SymbolProperties struct {
	// Authority Uppercase string
	Authority string `json:"authority"`

	// Symbol Uppercase string
	Symbol string `json:"symbol"`
}

// Limit defines model for Limit.
type Limit = int32

// Offset defines model for Offset.
type Offset = int32

// EntryLookupKey defines model for entryLookupKey.
type EntryLookupKey string

// EntryLookupValue defines model for entryLookupValue.
type EntryLookupValue = string

// GetConsortiaParams defines parameters for GetConsortia.
type GetConsortiaParams struct {
	// Q keywords to filter by
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEntriesParams defines parameters for GetEntries.
type GetEntriesParams struct {
	// Q keywords to filter by
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Limit Limit for pagination
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for pagination (first item is 0)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// DeleteEntryParamsKey defines parameters for DeleteEntry.
type DeleteEntryParamsKey string

// GetEntryParamsKey defines parameters for GetEntry.
type GetEntryParamsKey string

// UpdateEntryParamsKey defines parameters for UpdateEntry.
type UpdateEntryParamsKey string

// AddConsortiumJSONRequestBody defines body for AddConsortium for application/json ContentType.
type AddConsortiumJSONRequestBody = Consortium

// UpdateConsortiumJSONRequestBody defines body for UpdateConsortium for application/json ContentType.
type UpdateConsortiumJSONRequestBody = ConsortiumPatch

// AddEntryJSONRequestBody defines body for AddEntry for application/json ContentType.
type AddEntryJSONRequestBody = Entry

// UpdateEntryJSONRequestBody defines body for UpdateEntry for application/json ContentType.
type UpdateEntryJSONRequestBody = EntryPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns all consortia
	// (GET /consortia)
	GetConsortia(w http.ResponseWriter, r *http.Request, params GetConsortiaParams)
	// Creates a new consortium
	// (POST /consortia)
	AddConsortium(w http.ResponseWriter, r *http.Request)
	// Delete consortium by ID
	// (DELETE /consortia/{id})
	DeleteConsortium(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Returns a consortium by ID
	// (GET /consortia/{id})
	GetConsortium(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a consortium
	// (PATCH /consortia/{id})
	UpdateConsortium(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Returns all entries
	// (GET /entries)
	GetEntries(w http.ResponseWriter, r *http.Request, params GetEntriesParams)
	// Creates a new entry
	// (POST /entries)
	AddEntry(w http.ResponseWriter, r *http.Request)
	// Delete directory entry by ID
	// (DELETE /entries/{key}/{value})
	DeleteEntry(w http.ResponseWriter, r *http.Request, key DeleteEntryParamsKey, value EntryLookupValue)
	// Returns a directory entry by ID or symbol
	// (GET /entries/{key}/{value})
	GetEntry(w http.ResponseWriter, r *http.Request, key GetEntryParamsKey, value EntryLookupValue)
	// Update an entry
	// (PATCH /entries/{key}/{value})
	UpdateEntry(w http.ResponseWriter, r *http.Request, key UpdateEntryParamsKey, value EntryLookupValue)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConsortia operation middleware
func (siw *ServerInterfaceWrapper) GetConsortia(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetConsortiaParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsortia(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddConsortium operation middleware
func (siw *ServerInterfaceWrapper) AddConsortium(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddConsortium(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteConsortium operation middleware
func (siw *ServerInterfaceWrapper) DeleteConsortium(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteConsortium(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConsortium operation middleware
func (siw *ServerInterfaceWrapper) GetConsortium(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsortium(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateConsortium operation middleware
func (siw *ServerInterfaceWrapper) UpdateConsortium(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateConsortium(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntries operation middleware
func (siw *ServerInterfaceWrapper) GetEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntriesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddEntry operation middleware
func (siw *ServerInterfaceWrapper) AddEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key DeleteEntryParamsKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// ------------- Path parameter "value" -------------
	var value EntryLookupValue

	err = runtime.BindStyledParameterWithOptions("simple", "value", r.PathValue("value"), &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "value", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEntry(w, r, key, value)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntry operation middleware
func (siw *ServerInterfaceWrapper) GetEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key GetEntryParamsKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// ------------- Path parameter "value" -------------
	var value EntryLookupValue

	err = runtime.BindStyledParameterWithOptions("simple", "value", r.PathValue("value"), &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "value", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntry(w, r, key, value)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key UpdateEntryParamsKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// ------------- Path parameter "value" -------------
	var value EntryLookupValue

	err = runtime.BindStyledParameterWithOptions("simple", "value", r.PathValue("value"), &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "value", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEntry(w, r, key, value)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/consortia", wrapper.GetConsortia)
	m.HandleFunc("POST "+options.BaseURL+"/consortia", wrapper.AddConsortium)
	m.HandleFunc("DELETE "+options.BaseURL+"/consortia/{id}", wrapper.DeleteConsortium)
	m.HandleFunc("GET "+options.BaseURL+"/consortia/{id}", wrapper.GetConsortium)
	m.HandleFunc("PATCH "+options.BaseURL+"/consortia/{id}", wrapper.UpdateConsortium)
	m.HandleFunc("GET "+options.BaseURL+"/entries", wrapper.GetEntries)
	m.HandleFunc("POST "+options.BaseURL+"/entries", wrapper.AddEntry)
	m.HandleFunc("DELETE "+options.BaseURL+"/entries/{key}/{value}", wrapper.DeleteEntry)
	m.HandleFunc("GET "+options.BaseURL+"/entries/{key}/{value}", wrapper.GetEntry)
	m.HandleFunc("PATCH "+options.BaseURL+"/entries/{key}/{value}", wrapper.UpdateEntry)

	return m
}

type GetConsortiaRequestObject struct {
	Params GetConsortiaParams
}

type GetConsortiaResponseObject interface {
	VisitGetConsortiaResponse(w http.ResponseWriter) error
}

type GetConsortia200JSONResponse []Consortium

func (response GetConsortia200JSONResponse) VisitGetConsortiaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConsortia400TextResponse string

func (response GetConsortia400TextResponse) VisitGetConsortiaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetConsortia401TextResponse string

func (response GetConsortia401TextResponse) VisitGetConsortiaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type GetConsortia500TextResponse string

func (response GetConsortia500TextResponse) VisitGetConsortiaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type AddConsortiumRequestObject struct {
	Body *AddConsortiumJSONRequestBody
}

type AddConsortiumResponseObject interface {
	VisitAddConsortiumResponse(w http.ResponseWriter) error
}

type AddConsortium201JSONResponse Id

func (response AddConsortium201JSONResponse) VisitAddConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddConsortium400TextResponse string

func (response AddConsortium400TextResponse) VisitAddConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type AddConsortium401TextResponse string

func (response AddConsortium401TextResponse) VisitAddConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type AddConsortium500TextResponse string

func (response AddConsortium500TextResponse) VisitAddConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type DeleteConsortiumRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteConsortiumResponseObject interface {
	VisitDeleteConsortiumResponse(w http.ResponseWriter) error
}

type DeleteConsortium204Response struct {
}

func (response DeleteConsortium204Response) VisitDeleteConsortiumResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteConsortium400TextResponse string

func (response DeleteConsortium400TextResponse) VisitDeleteConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type DeleteConsortium401TextResponse string

func (response DeleteConsortium401TextResponse) VisitDeleteConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type DeleteConsortium500TextResponse string

func (response DeleteConsortium500TextResponse) VisitDeleteConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type GetConsortiumRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetConsortiumResponseObject interface {
	VisitGetConsortiumResponse(w http.ResponseWriter) error
}

type GetConsortium200JSONResponse Consortium

func (response GetConsortium200JSONResponse) VisitGetConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConsortium400TextResponse string

func (response GetConsortium400TextResponse) VisitGetConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetConsortium401TextResponse string

func (response GetConsortium401TextResponse) VisitGetConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type GetConsortium404TextResponse string

func (response GetConsortium404TextResponse) VisitGetConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type GetConsortium500TextResponse string

func (response GetConsortium500TextResponse) VisitGetConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateConsortiumRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateConsortiumJSONRequestBody
}

type UpdateConsortiumResponseObject interface {
	VisitUpdateConsortiumResponse(w http.ResponseWriter) error
}

type UpdateConsortium204Response struct {
}

func (response UpdateConsortium204Response) VisitUpdateConsortiumResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateConsortium400TextResponse string

func (response UpdateConsortium400TextResponse) VisitUpdateConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateConsortium401TextResponse string

func (response UpdateConsortium401TextResponse) VisitUpdateConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateConsortium404TextResponse string

func (response UpdateConsortium404TextResponse) VisitUpdateConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateConsortium500TextResponse string

func (response UpdateConsortium500TextResponse) VisitUpdateConsortiumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type GetEntriesRequestObject struct {
	Params GetEntriesParams
}

type GetEntriesResponseObject interface {
	VisitGetEntriesResponse(w http.ResponseWriter) error
}

type GetEntries200JSONResponse EntriesResponse

func (response GetEntries200JSONResponse) VisitGetEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEntries400TextResponse string

func (response GetEntries400TextResponse) VisitGetEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetEntries401TextResponse string

func (response GetEntries401TextResponse) VisitGetEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type GetEntries500TextResponse string

func (response GetEntries500TextResponse) VisitGetEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type AddEntryRequestObject struct {
	Body *AddEntryJSONRequestBody
}

type AddEntryResponseObject interface {
	VisitAddEntryResponse(w http.ResponseWriter) error
}

type AddEntry201JSONResponse Id

func (response AddEntry201JSONResponse) VisitAddEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddEntry400TextResponse string

func (response AddEntry400TextResponse) VisitAddEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type AddEntry401TextResponse string

func (response AddEntry401TextResponse) VisitAddEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type AddEntry500TextResponse string

func (response AddEntry500TextResponse) VisitAddEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type DeleteEntryRequestObject struct {
	Key   DeleteEntryParamsKey `json:"key"`
	Value EntryLookupValue     `json:"value"`
}

type DeleteEntryResponseObject interface {
	VisitDeleteEntryResponse(w http.ResponseWriter) error
}

type DeleteEntry204Response struct {
}

func (response DeleteEntry204Response) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEntry400TextResponse string

func (response DeleteEntry400TextResponse) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type DeleteEntry401TextResponse string

func (response DeleteEntry401TextResponse) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type DeleteEntry500TextResponse string

func (response DeleteEntry500TextResponse) VisitDeleteEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type GetEntryRequestObject struct {
	Key   GetEntryParamsKey `json:"key"`
	Value EntryLookupValue  `json:"value"`
}

type GetEntryResponseObject interface {
	VisitGetEntryResponse(w http.ResponseWriter) error
}

type GetEntry200JSONResponse Entry

func (response GetEntry200JSONResponse) VisitGetEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEntry400TextResponse string

func (response GetEntry400TextResponse) VisitGetEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetEntry401TextResponse string

func (response GetEntry401TextResponse) VisitGetEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type GetEntry404TextResponse string

func (response GetEntry404TextResponse) VisitGetEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type GetEntry500TextResponse string

func (response GetEntry500TextResponse) VisitGetEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateEntryRequestObject struct {
	Key   UpdateEntryParamsKey `json:"key"`
	Value EntryLookupValue     `json:"value"`
	Body  *UpdateEntryJSONRequestBody
}

type UpdateEntryResponseObject interface {
	VisitUpdateEntryResponse(w http.ResponseWriter) error
}

type UpdateEntry204Response struct {
}

func (response UpdateEntry204Response) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateEntry400TextResponse string

func (response UpdateEntry400TextResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateEntry401TextResponse string

func (response UpdateEntry401TextResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateEntry404TextResponse string

func (response UpdateEntry404TextResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(404)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateEntry500TextResponse string

func (response UpdateEntry500TextResponse) VisitUpdateEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Returns all consortia
	// (GET /consortia)
	GetConsortia(ctx context.Context, request GetConsortiaRequestObject) (GetConsortiaResponseObject, error)
	// Creates a new consortium
	// (POST /consortia)
	AddConsortium(ctx context.Context, request AddConsortiumRequestObject) (AddConsortiumResponseObject, error)
	// Delete consortium by ID
	// (DELETE /consortia/{id})
	DeleteConsortium(ctx context.Context, request DeleteConsortiumRequestObject) (DeleteConsortiumResponseObject, error)
	// Returns a consortium by ID
	// (GET /consortia/{id})
	GetConsortium(ctx context.Context, request GetConsortiumRequestObject) (GetConsortiumResponseObject, error)
	// Update a consortium
	// (PATCH /consortia/{id})
	UpdateConsortium(ctx context.Context, request UpdateConsortiumRequestObject) (UpdateConsortiumResponseObject, error)
	// Returns all entries
	// (GET /entries)
	GetEntries(ctx context.Context, request GetEntriesRequestObject) (GetEntriesResponseObject, error)
	// Creates a new entry
	// (POST /entries)
	AddEntry(ctx context.Context, request AddEntryRequestObject) (AddEntryResponseObject, error)
	// Delete directory entry by ID
	// (DELETE /entries/{key}/{value})
	DeleteEntry(ctx context.Context, request DeleteEntryRequestObject) (DeleteEntryResponseObject, error)
	// Returns a directory entry by ID or symbol
	// (GET /entries/{key}/{value})
	GetEntry(ctx context.Context, request GetEntryRequestObject) (GetEntryResponseObject, error)
	// Update an entry
	// (PATCH /entries/{key}/{value})
	UpdateEntry(ctx context.Context, request UpdateEntryRequestObject) (UpdateEntryResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetConsortia operation middleware
func (sh *strictHandler) GetConsortia(w http.ResponseWriter, r *http.Request, params GetConsortiaParams) {
	var request GetConsortiaRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConsortia(ctx, request.(GetConsortiaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConsortia")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConsortiaResponseObject); ok {
		if err := validResponse.VisitGetConsortiaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddConsortium operation middleware
func (sh *strictHandler) AddConsortium(w http.ResponseWriter, r *http.Request) {
	var request AddConsortiumRequestObject

	var body AddConsortiumJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddConsortium(ctx, request.(AddConsortiumRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddConsortium")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddConsortiumResponseObject); ok {
		if err := validResponse.VisitAddConsortiumResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteConsortium operation middleware
func (sh *strictHandler) DeleteConsortium(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteConsortiumRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteConsortium(ctx, request.(DeleteConsortiumRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteConsortium")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteConsortiumResponseObject); ok {
		if err := validResponse.VisitDeleteConsortiumResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConsortium operation middleware
func (sh *strictHandler) GetConsortium(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetConsortiumRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConsortium(ctx, request.(GetConsortiumRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConsortium")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConsortiumResponseObject); ok {
		if err := validResponse.VisitGetConsortiumResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateConsortium operation middleware
func (sh *strictHandler) UpdateConsortium(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateConsortiumRequestObject

	request.Id = id

	var body UpdateConsortiumJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateConsortium(ctx, request.(UpdateConsortiumRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateConsortium")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateConsortiumResponseObject); ok {
		if err := validResponse.VisitUpdateConsortiumResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntries operation middleware
func (sh *strictHandler) GetEntries(w http.ResponseWriter, r *http.Request, params GetEntriesParams) {
	var request GetEntriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntries(ctx, request.(GetEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEntriesResponseObject); ok {
		if err := validResponse.VisitGetEntriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddEntry operation middleware
func (sh *strictHandler) AddEntry(w http.ResponseWriter, r *http.Request) {
	var request AddEntryRequestObject

	var body AddEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddEntry(ctx, request.(AddEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddEntryResponseObject); ok {
		if err := validResponse.VisitAddEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEntry operation middleware
func (sh *strictHandler) DeleteEntry(w http.ResponseWriter, r *http.Request, key DeleteEntryParamsKey, value EntryLookupValue) {
	var request DeleteEntryRequestObject

	request.Key = key
	request.Value = value

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEntry(ctx, request.(DeleteEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEntryResponseObject); ok {
		if err := validResponse.VisitDeleteEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntry operation middleware
func (sh *strictHandler) GetEntry(w http.ResponseWriter, r *http.Request, key GetEntryParamsKey, value EntryLookupValue) {
	var request GetEntryRequestObject

	request.Key = key
	request.Value = value

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntry(ctx, request.(GetEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEntryResponseObject); ok {
		if err := validResponse.VisitGetEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateEntry operation middleware
func (sh *strictHandler) UpdateEntry(w http.ResponseWriter, r *http.Request, key UpdateEntryParamsKey, value EntryLookupValue) {
	var request UpdateEntryRequestObject

	request.Key = key
	request.Value = value

	var body UpdateEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEntry(ctx, request.(UpdateEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateEntryResponseObject); ok {
		if err := validResponse.VisitUpdateEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaS2/jOBL+KwRngd4FtG1nJjsH35zHLoLJToJ57CXIgRZLMccSqZBUuoXA/33Bh2w9",
	"KFlJ23k0ckpMUsWPVV8Vq0p6xLHIcsGBa4VnjzgnkmSgQdpflyxj2vxDQcWS5ZoJjmduGCVCopzcMU7s",
	"cISZmbsvQJY4wpxkgGc4tRIirOIlZMSJSkiRajw7mkY4ETIjGs8w4/qnH3GEM/KVZUVmZqfTCGeMu5/T",
	"COsyB7cS7kDi9TrCV0miIADQjbcQor8nTCqNmIYMMYWm/+jBLJzUOuguzmFgwLUsL4VYFfkvUHYB/gIl",
	"0gKlQqxQkSO7PELA9BIk+sToJyQk+qTKbCHSTxXMnOjlFuUKDGQJ9wWTQPFMywLqkIEbeDd4Uf6TURyZ",
	"v04evt1AVloyftdG/D+SFtDFbIeRSBCjBp0TZk5B4hiUcodAizIM98EKHQLcxrSuJi0V5wtRWEvnUuQg",
	"NQM7HIuCBwjwh9AkRbzIFiAtZA2ZQowjvQQkQRkCNtn38zHuWjLCHL7qS8ZXISfgK3N6I9GsMkyz6nHi",
	"Fe5oOcK5hIfd0swqJgq1W+K6rs8br4ytecXiL4i12XhOqQRlNUbS9CrBs5u2JhntovqTs/sCkOXPRllF",
	"YX9LIPSKp2VlyGFojOLbdfSI/yYhwTP8w2QbdibeyhMP8noLa327xX5aPdAlgYL7Lvbf4b4AHkPFAhMM",
	"hKRg4KFa0AsEoS4N3MjWqf5YCimKu2VCpCH1pYhJyrSh/pya0KC0JJo9wFwCwRG+FkqT9FRQs/jUWEmW",
	"/teVcfmAS0beYwKO0dSsObx/unpmgAHXRMfLfdKg67XfYuTrBpYmMtLigYNrHNv8M2LPLYM2FsVESlKG",
	"LHzmr6kI/75keW4OF+ETlqbuvz6ztYxjZ0PmOBVcCamZ2ax9UBtIG7dOWNfRsLGAa5YwkAGjZYxfAr/T",
	"Szw72unJVQhvb3TGVJ6SEtnZtsyd0cBLHdbNhq0jFcSLNCWLFA57kg7gc64lA/UbqFxwBQHqVpfXIEvt",
	"ImPVitOjyH1uldFhdEvjDkEl+7bnEGWv17kfTbXNqylElBIxIxoo+sL0Eukl8/kAjp7koiHPjAXXJNa/",
	"Bk1nRs0V6RehHKSyyeigEaOmlA4fQBOWAkW1YbOJuZyNV+nSzyyAokXZPO6OjSEjLO1u+V/C+OYQbk1D",
	"1M8hUZzmgvlA2L785AOLDVq/ZA8m8jLPvciQqfacQ/T5a2V0Yw/GlWa6cCaSaCEJj/3pKJMQayFLn5pW",
	"NlO7reSS25Bi3cQ+1OmS8V2OOxwqrdP2RMmG5z7FCZ28dW847fPMpk53xuKWCz7x6Y0fNZ1k93N1p3kO",
	"70drhwfVMkS1J/BmJIrQbXVBu1z51qyvm+wHNm4HkDddjLSt3spXg6R4xbT6iXB3p9mBwmNL6c5ElT0P",
	"693nV75WqTYKUsUFx7fNEOeIbU3X3PM1+TAEbsj6hV4KaUrZLrw8BxkTBcij6A1mz3m2XdU6QVEN0K1t",
	"CTGeCMs0pk3Qw2fVJc/UEs2vL0wRDFK5bY8+Tz9PDS6RAyc5wzP8kx2KbHfKnngS+3LDNqHuQu3E30AX",
	"kitE0hRtVtvso1Ag0ZKoqgemxWdsd5O25WhCLf4P6NPNFlGjw3rT3mkF5RchqRGEEpZqkLWGWqtNeY8H",
	"umcRVrq0CjJMwoYuzZ18o7XWI/NdJrO1tAce3dLd2UBZ3xrruurIKv3H6dR177j2HR2S5ymLrdYmfymX",
	"Emx3GHUz1mrqblbVTjhqVSZKmdKowmeePe7A0/BVT/KUsBawQNOyuc0JocgQG5R2ko/2JfnfQi4YpcCN",
	"3H/tD/EF1yA5SZEC+QASgZTCdbVVkWXEFIlhj7AdTqECDnQqgWhTJyIOXzYPFFnHV+aUntZnveZOBC2f",
	"xJexNBmkhRaIUNrpWa87XD7aG7YLugPThqURThlfWQC1AFNkJ+XFmRls6vWuvqQVhNxlZGA50Z8XgpY/",
	"TJiF8l6cYe7iLwXOgL6CQ/Qy3CzbXjGTR0bXzj9S0NA11Jkd77VV58K4OPPdjxppvezgaxhGB9/B7Eo7",
	"unH8uOvtNTQOCsUfNBpHI2f+uj0XJbo4M0h8ZtKbWzyPKwmYRPVlqDJ9+RD+vi/1Y+dd+5D7q9AoEQWn",
	"r5ksBHmdV6VSu2KgREPjmU624NZ8mwMUVsbhPOCQ+YtvAnWt4hRDUcIgpWpEBhOI4jUvcjp6x1H8O3Gk",
	"kE/Y/ALcC6hRBaxfixIpMlvDqlJpMP8S/ZSa1r/0es2KNuQlWzAT9/XSiIX+M6KDXlntd4QBCthm/jst",
	"Rl87cQowfGw5Wr216VSi537iEEHcv7XtI8GbKT0dnJ6q0072Fpzb2fH1ZuRj3OZldFNqUZv8KGIPXMSC",
	"p+j2fpk8rqBcTx7tV0YjytiQoW52RuPWt5Mj4nfn28VxdWr1VvijRH1Gidp+ub6zTn1LZJi+VBx///f4",
	"d1eDBom7/aB5REnKe1KGP3tvpxfk+YFSlYOWms4QH1Xm26oy+SYDMNN2vaNyIVM8wxOpKJN4fbv+fwAA",
	"AP//Mvbv60QyAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
