# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build-test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - '**.xsd'
      - '**.html'
      - '**/Dockerfile' #run this workflow first to ensure tests are passing
      - '**/chart/**' #trigger also when chart templates chnage to force republish
      - '.github/**' #trigger when pipeline changes
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'
      - '**.xsd'
      - '**.html'
      - '**/Dockerfile' #run this workflow first to ensure tests are passing
      - '**/chart/**' #trigger also when chart templates change to force republish
      - '.github/**' #trigger when pipeline changes
  release:
    types: [published]

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: [broker]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint ${{ matrix.modules }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.modules }}
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-package: ./...
          work-dir: ${{ matrix.modules }}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install xsltproc
      run: sudo apt-get install -y xsltproc

    - name : Ensure sqlc is installed
      uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.25.0'

    - name: Print sqlc version
      run: sqlc version

    - name: Build
      run: make all

    - name: Test
      run: make check
